### ISSUE TITLE
[CS 1.6] Wad file downloads still wont work.

### ISSUE THREAD

**Issue by Krapfenmann** [ValveSoftware/halflife#1026]
Well, 

I don't know why this happens to my server, but on my gameserver (IP: 84.201.16.6:27015) there is still this Problem:

https://github.com/ValveSoftware/halflife/issues/160

Map changes to fy_iceworld and attempt to load de_vegas.wad, which is needed to play this map. There is a download bar and this goes up to 100% ... but then the game freezes. Then you have to quit the game with the task manager and next time you connect it crashes on load and i get the error "Could not open de_vegas.wad" which is pretty weird, cause it seemed to take 1 min to load this map. 

A look in the cstrike_downloads folder and there is a new folder named "de_vegas.wad" ... so this problem still there? 

My Server is on build 5956 - 1.2.2.7 /stdio

**Comment by miguelk5** [comment]
Quick fix for this issue !
Since defintly this bug still happening  , but just with some map that includes .wad files like as_tundra. The fix is just use fast download feature :

cstrike / server.cfg 

add : sv_downloadurl "http://yourwebsite/my_cstrike/"

Then , create such directory on the root of your webspace .

Add there each .wad file that any map could need , important respect folder structure , example (sounds/monster.wav   , overview/map.bmp)   

Also i copied all needed files inside  a folder called "my_cstrike/cstrike_downloads"  because the steam version of CS1.6 download files inside cstrike_downloads folder

**Comment by kisak-valve** [comment]
Per https://github.com/ValveSoftware/halflife/issues/1425#issuecomment-489334822, is anyone still experiencing this issue?

**Comment by kisak-valve** [comment]
Closing per https://github.com/ValveSoftware/halflife/issues/1425#issuecomment-489334822.
