### ISSUE TITLE
OpenGL lag on Intel GMA notebook

### ISSUE THREAD

**Issue by L4Z10** [ValveSoftware/halflife#1227]
Good afternoon mates!

I have read an issue about this problem, but the reporting user was not too helpful.

I try to explain it in a little more detailed way.

I'm playing periodically CS 1.6, last time i played it was before the update, that took d3d away.

I have a Samsung NP300E5Z notebook. It has Intel B950 cpu, 4 gb ram, and a dual videocard system, with an Intel HD 3000 and a Geforce gt 520 mx.

I cannot use the dedicated gpu as there is no option for that in the driver. (in other games, i can switch between the 2 gpus.)

When i play i get similar or rather less fps, than in source(w geforce). When somebody turns on the flashlight, or a grenade is exploding in front of me i lose 70-80% of my fps whatever graphics settings I use. If I take it back to 640-480 low graphics, it drops from 100 fps to about 20, on maximum settings it goes from 50-60 to 15. 

I tried all of these launch options: -console -noforcemspd -high -noipx -nojoy -nofbo -nomsaa and more which i cannot recall now, but none of them worked.

I tried modifying my integrated gpu's settings (only in wizard mode from performance to quality), but it didn't help either.

It is very funny (in a bad way) that though I can run Starcraft 2, but Counter Strike is unplayable.

Waiting for a good solution patiently,

Peter

**Comment by wokawoka** [comment]
Sorry for resurrecting this issue (after nearly 6 years) but I'm experiencing the same problem while playing an half-life mod (specifically deathmatch classic) on an intel hd4000.

Do you guys by chance know if a command to disable dynamic lighting or any methos to solve the struttering during explosions and light reflection exists?
I've already tried with all the console commands I could find but without any improvement.
Many thanks

**Comment by tschumann** [comment]
I think r_dynamic might turn off dynamic lighting.

**Comment by wokawoka** [comment]
Thanks for replying.
Unfortunately, as I also previously tried, the r_dynamic command doesn't solve the problem. Nothing changes between "r_dynamic 0" and  "r_dynamic 1".

**Comment by L4Z10** [comment]
I have never managed to solve the issue with steam version, had to find an earlier no-steam version where d3d was enabled.

**Comment by wokawoka** [comment]
mmm, ok ,but then would I be able to connect to servers and play online with such older non steam viersion that kept direct3d rendering?

On my laoptop there's no dedicated GPU, just the intel HD one, and I always enjoyed playing these HL1 mods for many many years always without problems. It's a real pity not being able to do so now (also because the system requirements to run them smoothly are extremely accessible).

From my experience no console command was able to remove the struttering during explosions and light reflections.
As a last test I'll try to fiddle a bit with the graphic card driver settings to see if I can improve the situation and eventually report back.

Thanks!
