### ISSUE TITLE
[TFC] Spy disguise not working after map change

### ISSUE THREAD

**Issue by pizzahut2** [ValveSoftware/halflife#1330]
On a fully updated SteamCmd Linux server without any plugins, it's not possible to disguise any more after a map change.

It can randomly start working again, but this isn't reproducible.

Protocol version 48
Exe version 1.1.2.2/Stdio (tfc)
Exe build: 17:45:07 Apr 25 2013 (6027)

Updated with these commands:

app_set_config 90 mod tfc
app_update 90 validate

Possibly related: bug fix for https://github.com/ValveSoftware/halflife/issues/1003

Another report here:
http://steamcommunity.com/app/20/discussions/0/864975632348324162/

**Comment by Arkshine** [comment]
It looks like `CBasePlayer::flLastDisguesChange` in `CBasePlayer;;TeamFortress_SpyDisguise()` is not reset.

Code starts like this:
```C
if (gpGlobals->time - CBasePlayer::flLastDisguesChange >= 1.0)
{
    CBasePlayer::flLastDisguesChange = gpGlobals->time;
```
I would assume at map change, `flLastDisguesChange` holds the previous value, and thus, the check won't be true unless `gpGlobals->time` unless value is > to previous value of `flLastDisguesChange + 1`.

**Comment by dazultra** [comment]
This bug is very much still an issue in the current stable version and is affecting a surge of players from the latest Steam Summer Sale.
 
Protocol version 48
Exe version 1.1.2.2/Stdio (tfc)
Exe build: 13:12:29 Aug 29 2013 (6153)

Concerning the sourcecode @Arkshine is quoting, I can't seem to find public reference to that. Is TFC itself closed source?

**Comment by tschumann** [comment]
Team Fortress Classic is closed source but the snippet is probably from reverse engineering the Linux server .so
Is it possible to fix this with a plugin?

**Comment by SamVanheer** [comment]
Arkshine is correct. flLastDisguesChange is a static local variable in the disguise function. It's never reset (and can't be reset since it's only accessible to that function) so it will stay at its last value from the previous map.

It's odd that they're using a static local for this. I'd have thought a member variable would be better suited here, since this affects all spies. If you timed it right, you could detect when another spy is disguising.

It's easy to fix and test, so hopefully whoever is assigned to this issue now will fix it.

**Comment by battlemint** [comment]
this bug still seems to be prevalent.  i experience it on some servers, and not on others.  what is the fix?  

thanks.

**Comment by pizzahut2** [comment]
@battlemint The work-around is to use an old binary for TFC, from before SteamCMD was rolled out.

https://web.archive.org/web/20150418185206/http://forums.steampowered.com/forums/showthread.php?p=35217128

**Comment by battlemint** [comment]
Thank you, pizzahut!

**Comment by pizzahut2** [comment]
Can someone confirm whether this is fixed now? After today's update, I tried reproducing the bug on Windows with listen server (TFC main menu), SteamCMD and Steam Tools (Steam library). The bug didn't occur.

The double shoot bug is still present though.

**Comment by pizzahut2** [comment]
I have no idea how I "unassigned alfred-valve". But as it's fixed now anyway, no matter. Closing issue.

**Comment by APGRoboCop** [comment]
How is that possible?
