### ISSUE TITLE
Server redirection exploit (AMXX example)

### ISSUE THREAD

**Issue by shavitush** [ValveSoftware/halflife#1480]
Old server redirection was:
client_cmd( client, "connect XX.XX.XX.XX:XXXXX" );

New exploit:
client_cmd( client, ";^"Connect^" XX.XX.XX.XX:XXXXX" );

Won't it be better to do like the askconnect_accept command in Source Engine games and the server redirection box? Feels less hacky.

**Comment by illiftwhat** [comment]
This command is not blocked and is bypass by all server... the server browser is just full of redirection server

client_cmd(id, "wait;wait;wait;wait;wait;^"connect^" %s",server);

This exploit is never fixed since 2014...

**Comment by di57inct** [comment]
@illiftwhat Oh, there are far worse things than that which still work. I can make a script which will infect your PC through any GoldSrc engine game on Steam. This is Valve we're talking about here. Lower your expectations.

**Comment by illiftwhat** [comment]
there are 25,000 players on counter-strike (steam stats), the game is still on sale in the steam store

And Valve made ​​the ostrich... They just want to make money with CSGO and skin

**Comment by blatouchm** [comment]
Lol, just dont play on this shit servers and keep other good. Valve now disable connect command and redirect no more works = bullshit.

**Comment by SamVanheer** [comment]
So you're saying this issue has been fixed? If so this issue can be closed.

**Comment by oaus** [comment]
> So you're saying this issue has been fixed? If so this issue can be closed.

Yes it's fixed now.

**Comment by sloptop-the-terrible** [comment]
Thread timeline, for the record:
2014: "This dream will never be a reality."
2016: "This exploit is never fixed since 2014."
2019: "Yes it's fixed now."
2026: the game is still on sale, and Valve is still the ostrich.

Somebody should really tell GoldSrc players that the exploit was never the problem — the problem is that we all kept connecting to servers run by people who think xRedirect is a personality.
