### ISSUE TITLE
[CS 1.6] Custom sprays - not working "server failed to transmit file 'customization'"

### ISSUE THREAD

**Issue by Kremnev** [ValveSoftware/halflife#1485]
Hi, i testing hlds clear build (6027,6132 and 6153) (windows)
And all have problem is custom spray.

``` ruby
Requesting tempdecal.wad from server
Error: server failed to transmit file 'customization'
```

server.cfg

``` ruby
sv_allowupload "1"
sv_allowdownload "1"
sv_send_resources "1"
sv_send_logos    "1"
```

Player connecting server, give tempdecal.wad in custom.hpk Server
Server don't transmit custom.hpk all players
That is don't update custom.hpk on the client side
Server custom.hpk have all custom sprays players
But why it can not transmit client

``` ruby
Counter-Strike Client
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
Exe build: 13:14:12 Aug 29 2013 (6153)
```

And old HLDS (build 5787) no have this problem, even playing with new client

**Comment by Wasdsensei** [comment]
At risk of saying "bump" anyone have any step-by-step instructions as to how to restore this functionality within a mod from the code side? We added some "lore friendly" spray paints for our Half-Life MMO and they were working at the time.

On the other hand, we addded these in 2015:
https://www.msremake.com/forums/viewtopic.php?f=34&t=9167&p=149571&hilit=lore+relevant+logos+spray+paints#p149571

And they worked at the time, only more recently has the customization failed.

**Comment by pizzahut2** [comment]
This seems to be fixed in the TFC beta, thanks! :D

**Comment by mikela-valve** [comment]
Oh, you're right it is! I was a bit surprised when I saw your comment as I had another change staged to fix this that I hadn't added yet but it was actually the fix to #2109 that fixed this issue as well.

`IsSafeFileToDownload` had a check in it to ensure that resources downloaded both had a file extension and had an extension that was exactly three characters. That broke downloaded MD5 hash files as @LevShisterov mentions above which broke propagation of custom sprays. I removed that check altogether to let files like .sc through but that had the additional benefit of fixing this issue. 

This fix was in the engine, so it should be fixed in the public versions of all GoldSrc games already if someone would like to verify that for me before I close the issue.

**Comment by SamVanheer** [comment]
It seems to be working now, i'm not getting any errors about customization in the console, and i can see other players' spraypaint. This should be verified by someone with a custom spray as well though (meaning not a monochrome spray).

**Comment by mikela-valve** [comment]
I think this issue is fixed based on comments I've seen on the Steam forums.

**Comment by fysiks1** [comment]
This is definitely not fixed in Day of Defeat.  I've not seen custom sprays working for years.
