### ISSUE TITLE
cl_filterstuffcmd bypass problem

### ISSUE THREAD

**Issue by serfreeman1337** [ValveSoftware/halflife#1497]
You can bypass any slowhack protection by sending a specified message for the client. This messages can be done by AMX Mod X plugins. 

Here is some stocks for AMXX:

```
stock SendCmd_1( id , text[] ) {
      message_begin( MSG_ONE, 51, _, id )
      write_byte( strlen(text) + 2 )
      write_byte( 10 )
      write_string( text )
      message_end()
}
```

Or another way with CBuf_Exute using \x0A instead of ';' we can forward cmds to CBuf_AddText.

```
stock SendCmd_2( id , text[] ) {
   static cmd_line[1024]
   message_begin( MSG_ONE, 9, _, id )
   format( cmd_line , sizeof(cmd_line)-1 , "%s%s" , "^n" , text )
   write_string( cmd_line )
   message_end()
}
```

**Comment by seroff** [comment]
Good, Nice!

**Comment by satnatantas** [comment]
I confirm it and you'd better make it work.

**Comment by SamVanheer** [comment]
The first approach abuses the director command message to stuff text from the local client's side. Special case code can be written in CL_Parse_Director:
```
void CL_Parse_Director()
{
  int iSize;
  byte *pbuf;

  //Start new locals - Solokiller
  int old_msg_readcount = msg_readcount;
  qboolean bIsValidCommand = true;
  int command;
  //End new locals - Solokiller

  iSize = MSG_ReadByte();
  pbuf = &net_message.data[msg_readcount];

  //Verify that stuff text commands are not cheating.
  command = MSG_ReadByte();

  if( command == DRC_CMD_STUFFTEXT )
  {
    //Filter command here, never allow client to handle it if it fails check.
    bIsValidCommand  = ValidStuffText( MSG_ReadString() );
  }

  //Restore readcount
  msg_readcount = old_msg_readcount;

  if( bIsValidCommand  )
  {
    //This was already here
    ClientDLL_DirectorMessage( iSize, pbuf );
  }

  msg_readcount += iSize;
}
```

`ValidStuffText` is used by message 9 (stufftext) already, so the second approach is already secure.

Trivially easy to fix.

**Comment by WPMGPRoSToTeMa** [comment]
You can't filter only by one received `svc_stufftext`, because command can be sent partially. You should add some label before server command and after OR better to write commands received from server into another command buffer.

**Comment by SamVanheer** [comment]
Alright, so incoming strings should first be preprocessed to skip newlines that occur at the start.

```
int __cdecl ValidStuffText(const char *cmd)
{
  while( *cmd && *cmd == '\n' )
    ++cmd;
}
```

Should probably do a thorough check in the command buffer code to see if any other edge cases like this exist though.

**Comment by theAsmodai** [comment]
Not only '\n': https://github.com/ValveSoftware/halflife/issues/268#issuecomment-30529896

**Comment by SamVanheer** [comment]
I see, that's not quite as simple to fix. You could "fake" execute it first to parse out the wait commands, but that's not easy to do in this codebase. 
I suppose a special function could be used to execute the commands in a dummy environment so all internal commands like wait are parsed out and translated to the appropriate commands to, say, merge duplicates. You'd then have a list of commands like this:
```
wait x 5
command connect <args>
wait x 2
command name "you've been hacked"
```

Basically like that. Then you can just filter out illegal commands by pruning them from the list. 

It's costly compared to how it does things now, it might be cheaper to just stick in special commands in front and back that denote when the command came from the server (with special handling for the director message and other exploitable commands in official games), which would make the command processor filter them out. 
The commands themselves should not be legal to insert, so any insert calls that don't insert those commands (all of them) should filter them. Ideally i'd say Cbuf_AddText and Cbuf_InsertText should should insert those tokens while filtering them out from the actual inputs, using a global to mark whether it should do so. This will likely increase the buffer usage a bit, so barring a full rewrite this is not easy to fix.

Of course, a complete rewrite is probably saner than trying to work around it. I'd rewrite it to preparse the commands and store the origin of the message (again with special handling for directormessage) so that the parser will filter them out. That would increase memory usage, which means out of memory issues will show up more frequently due to how the engine manages memory. I suppose you could statically allocate command buffers and define a hardcoded number of commands each can have, not sure.

Maybe take Source's version?

**Comment by WPMGPRoSToTeMa** [comment]
You can just write commands received from server into another command buffer and execute it after executing default command buffer.

**Comment by SamVanheer** [comment]
That also works :P

**Comment by WPMGPRoSToTeMa** [comment]
If you want to use marks method, you can mark text from the server with zero bytes.
Something like this:
`lastinv\n` is received from the client console, then server sends partially `connect github.com\n` as `con` and `nect github.com\n`, then client puts in console `weapon_knife\n`.
So in buffer you will see:
`lastinv\n\0con\0\0nect github.com\n\0weapon_knife\n`
When you puts new text received from the server you can also check for previous symbol was `\0`.
So you will get this:
`lastinv\n\0connect github.com\n\0weapon_knife\n`

**Comment by SamVanheer** [comment]
Looks like the latest update fixes this using my suggestion as a base, but there are some problems with it.

See #2109, #2108, #2106

**Comment by TIVRSG** [comment]
Would be nice if something would happen with this. Seemingly more, and more server are using this.
Any Valve reactions?

**Comment by afwn90cj93201nixr2e1re** [comment]
@kisak-valve done.

**Comment by pizzahut2** [comment]
Question, shouldn't sending "retry" to the client work if cl_filterstuffcmd is 0? Because when testing with a current Windows stand-alone server (using steamcmd), it was blocked. (Can anyone confirm this?)

I could really need the "retry" command to circumvent a bug in AMXX where normal players occasionally get assigned a 127.0.0.1 IP, presumably because AMXX thinks they are bots. https://github.com/alliedmodders/amxmodx/issues/848 This bug can circumvented either by re-writing all plugins which use "get_user_ip", or for a "catch all" my idea was to send the "retry" command to clients when this happens.

**Comment by pizzahut2** [comment]
@kisak-valve @Solokiller Question, shouldn't sending "retry" to the client work if cl_filterstuffcmd is 0? Because when testing with a current Windows stand-alone server (using steamcmd), it was blocked. (Can anyone confirm this?)

I could really need the "retry" command to circumvent a bug in AMXX where normal players occasionally get assigned a 127.0.0.1 IP, presumably because AMXX thinks they are bots. https://github.com/alliedmodders/amxmodx/issues/848 This bug can circumvented either by re-writing all plugins which use "get_user_ip", or for a "catch all" my idea was to send the "retry" command to clients when this happens.

**Comment by Solokiller** [comment]
`retry` is one of the commands that are always blocked regardless of the cvar setting.

**Comment by pizzahut2** [comment]
Thanks. Since the dev wiki has it different, I was hoping it got blocked by mistake. Guess not then. :) 

https://developer.valvesoftware.com/wiki/Admin_Slowhacking#Blocking
