### ISSUE TITLE
[CS 1.6] Bug with WAD files downloading

### ISSUE THREAD

**Issue by Zero-Tolerance** [ValveSoftware/halflife#1526]
Critical bug with downloading WAD files from HLDS.

Clean and latest versions of HLDS and Counter-Strike:
HLDS:
Protocol version 48
Exe version 1.1.2.7 (cstrike)
Exe build: 17:46:18 Apr 25 2013 (6027)

Counter-Strike:
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
Exe build: 13:14:12 Aug 29 2013 (6153)

How to implement bug (filenames and paths without quotes):
1. Create new file in "cstrike/maps" directory of HLDS with name: "cs_assault.res".
2. Add one line into it: "cs_assault.wad".
3. Run HLDS with cs_assault map.
4. Remove "cstrike/cs_assault.wad" file in Counter-Strike game client.
5. Connect to server.
6. CS game client begin downloading "cs_assault.wad" file.
7. After downloading, CS game client got freeze (process not responding, crash).
8. Check "cstrike_downloads" directory of CS game client: you will see "cs_assault.wad" DIRECTORY (NOT FILE). This is reason of game client freeze.

![cs wad downloading bug](https://cloud.githubusercontent.com/assets/7841959/3222058/3303d1a6-f012-11e3-96e7-20404d2ee21c.gif)

Short video:
https://www.youtube.com/watch?v=WjFIYB44Pqg

Full video (with custom map example):
https://www.youtube.com/watch?v=Id1FQuT2Tao

**Comment by miguelk5** [comment]
Quick fix for this issue !
Since defintly this bug still happening  , but just with some map that includes .wad files like as_tundra. The fix is just use fast download feature :

cstrike / server.cfg 

add : sv_downloadurl "http://yourwebsite/my_cstrike/"

Then , create such directory on the root of your webspace .

Add there each .wad file that any map could need , important respect folder structure , example (sounds/monster.wav   , overview/map.bmp)   

Also i copied all needed files inside  a folder called "my_cstrike/cstrike_downloads"  because the steam version of CS1.6 download files inside cstrike_downloads folder

**Comment by WPMGPRoSToTeMa** [comment]
> Also i copied all needed files inside a folder called "my_cstrike/cstrike_downloads" because the steam version of CS1.6 download files inside cstrike_downloads folder

But it won't download them from `cstrike_downloads`.

**Comment by miguelk5** [comment]
Ok , then the cstrike_downloads folder is not needed , but use sv_downloadurl really fix this problem because the file is sent by http protocol and it copies without this bug

**Comment by kisak-valve** [comment]
Per https://github.com/ValveSoftware/halflife/issues/1425#issuecomment-489334822, is anyone still experiencing this issue?

**Comment by kisak-valve** [comment]
Closing per https://github.com/ValveSoftware/halflife/issues/1425#issuecomment-489334822.
