### ISSUE TITLE
Steam favorite ingame and outgame server browser problems ?

### ISSUE THREAD

**Issue by Freeman-AM** [ValveSoftware/halflife#1584]
Since two or three days there is big problem concerning steam favorite server list.

At least, it touch CS 1.6 servers.

Some servers appear and desappear for more than 30 sec of the steam favorite ingame and outgame server browser for more than 30 seconds but they are in fact online and currently running.

Some others often the empty ones, are not touched by this problem.

This bug touch many people and not only me.

**Comment by AMeEeRo** [comment]
Same here, i'm ViRuSeS btw Freeman i love you xD
I saw on a Russian forum that there is a private HLDS UDP Exploit that attacking all servers, Even steam only servers ... The problem that my server is under this attack too, And i don't know what to do, What the attacks do ? it makes server disappear from Favorites list, And no one can join it, after seconds it comes back then attacked again and again, And my server will be like crashed, I saw it down many times on GameTracker, Guys it's STEAM ONLY SERVERS problem

**Comment by Krapfenmann** [comment]
I also can confirm this. It is still there and since today it has been so worse, that i only could connect to it every 10 min with luck. Worst time was from 10 AM to 18 AM CET.

When connected everything seems fine. Even ping is great. Just <Server not responding>  in friends list. Gametracker also cannot find the server and our HLstatsX show ridiculous graphs.

Many server are affected by this but it seems not all. FTP connection works fine and without lags and im able to download all files very fast.  It has to be a steam issue and its since 1st or 2nd January 2015.

**Comment by Freeman-AM** [comment]
Come on valve please do something.
2 week of constant bug !!!

**Comment by prokki** [comment]
*push*

Same problem here. Sometimes everything is alright, but most of the times, i try to connect by console more than 10minutes before connecting. And after some map changes, everthings starts again.

**Comment by Freeman-AM** [comment]
again. seriously.

**Comment by Krapfenmann** [comment]
Annnd its again .this evening or better said: The whole day! .. so after i lost so many ranks in gametracker and other tracking pages, i could cry when i think of 5 years hard work getting from none to full house just reset to zero but hey ... here i am again reporting this issue for those which are asking me everyday "What can you do krapfenmann?" and all i can say is "Nothing but wait". Another month? Maybe 3? Or longer?? 
Before i get in rage, i calm myself down because our community STILL has this problem everyday and all those great guys there in CS 1.6 community manage to connect to our server even if it takes 2 hours for them just trying to connect.

So we are not alone: http://steamcommunity.com/app/10/discussions/0/627457481700313928/

Why on earth is this since maintenance at 2nd january 2015? There has not even been an cs update or? Please valve, tell us. At least tell us something even it is small, maybe that you recogniced the problem and working on it. But this is ruining most of the popular communitys out there and frustrating loayal players. Help us not to die! Thank you!

**Comment by fifka1002** [comment]
Will anyone review that issue? That's causing much trouble at my servers...

**Comment by Freeman-AM** [comment]
Fixed now.
