### ISSUE TITLE
Half-Life: I can't compile client.dll

### ISSUE THREAD

**Issue by headshoter** [ValveSoftware/halflife#1648]
i having this errors:

LINK||fatal error LNK1104: cannot open file '..\utils\vgui\lib\win32_vc6\vgui.obj'
LINK||fatal error LNK1104: cannot open file '..\lib\public\sdl2.obj'

those files are not included on SDK?

i have tryed with Visual C++ 6.0 and Visual C++ 2010

i use codeblocks to compile.

hope you can solve my problem.

From already thank you very much.

**Comment by JoelTroch** [comment]
Those files are included within the SDK.

On a fresk SDK (no edits), try opening the projects/vs2010/projects.sln
file with Visual C++ 2010, build the solution and it should work.

**Comment by headshoter** [comment]
thanks, now im getting this:
inputw32.obj||error LNK2019: unresolved external symbol __imp__GetCursorPos@4 referenced in function "unsigned long __stdcall MousePos_ThreadFunction(void *)" (?MousePos_ThreadFunction@@YGKPAX@Z)|

inputw32.obj||error LNK2019: unresolved external symbol __imp__SystemParametersInfoA@16 referenced in function _IN_ActivateMouse|

inputw32.obj||error LNK2019: unresolved external symbol __imp__SetCursorPos@8 referenced in function "void __cdecl IN_ResetMouse(void)" (?IN_ResetMouse@@YAXXZ)|

**Comment by JoelTroch** [comment]
Do you have the Service Pack 1 for Visual Studio 2010 installed? If no, try
to download and install it.

**Comment by headshoter** [comment]
installing..

so.. what software you use to edit/compile Half Life SDK?

i started using Visual C++ 6.0 on a virtual machine with Windows XP.

now i use codeblocks and steal the compilers from Visual C++ 6.0 and 2010 to work with it on Windows 7.

sorry my english sucks.

thanks mate.

**Comment by JoelTroch** [comment]
For this source code, I recommend the usage of Visual C++ 2010 SP1
compilers.

Visual C++ 6 compilers can still be used as "legacy" style, just make a
blank workspace, add the 2 DSPs projects to it and done.

Visual C++ 2012/2013 compilers can also be used by "converting" the VC++
2010 solution and projects, you may have an error about HSPRITE which can
be fixed by renaming HSPRITE to something else or by commenting it in the
concerned Windows's header file.

Visual C++ 2015 compilers requires a lot of stuff to be changed in order to
work (@malortie has made a fork about it if I remember correctly).

CodeBlocks should work as long as you setup the usage of VC++ 6/VC++ 2010
SP1/VC++ 2012/VC++ 2013 compilers.

**Comment by malortie** [comment]
@headshoter 

I have re-upload both [VS2013](https://github.com/malortie/halflife/tree/branch-malortie-vs-2013) and [VS2015](https://github.com/malortie/halflife/tree/branch-malortie-vs-2015) fixed versions.
They should compile fine. If not, please let me know.

**Comment by headshoter** [comment]
well, Visual C++ 2010 SP1 compiler, don't works for me, i will try with VS2015 and @malortie update.

thanks again.

**Comment by headshoter** [comment]
@JoelTroch @malortie thanks for help, now it compile fine with malortie update and vs2015.

thanks again mates, now can close it.
