### ISSUE TITLE
[SDK] how i can debug my mod?

### ISSUE THREAD

**Issue by headshoter** [ValveSoftware/halflife#1649]
first of all, sorry my english sucks.

well, as the title says, i need to debug a mod what i'm making.

i'm adding npcs to my mod and the last one crashes when they see me.
then, i need to see why that crash the game when they see another npc or player.

then i tried to do this commands,

developer 1
condebug
log on

and that's not worked at all, because don't catch what what's crashing the game, then i tryed to debug the game with MS 2015 debugging tool, but that's don't worked too.

now i come to us, to ask, how i can debug my mod?

any help?

thanks.

**Comment by tschumann** [comment]
I don't remember the specific steps but run Half-Life with debug builds of your .dll files, then through Visual Studio attach to hl.exe and cause the crash.

**Comment by headshoter** [comment]
how i do that?

**Comment by tschumann** [comment]
Which part? Might depend on your version of Visual Studio but I think it's in the Build or Debug menu that you Attach to Process.

**Comment by headshoter** [comment]
how to compile debug biuld

**Comment by headshoter** [comment]
well, with debug build i can see every execution of code, but it don't show whats happens at the moment of crash. and VS 2015 don't helps xD

**Comment by malortie** [comment]
@headshoter 

If you experience crashes in your mod, and assuming you have no changes to base classes such as
**CBaseMonster** , then I recommand you to check if you are using any possible invalid pointers. 

.i.e:

```cpp
CBaseMonster*  pMonster = pEnemy->MyMonsterPointer();

// Unverified pointer.
pMonster->pev->health = 0;

// Corrected. We validate to ensure pointer is not NULL.
if(pMonster)
   pMonster->pev->health = 0;

```

As for launching from Visual Studio, I invite you to read [Launching from Visual Studio](https://developer.valvesoftware.com/wiki/Launching_from_Visual_Studio) on VDC, you can apply the same procedure here.

.i.e:

In the **Command** field, enter:
> \<YourDriveLetter\>\Steam\steamapps\common\Half-Life\hl.exe


In the **Command line arguments**, enter:
> -game \<gamedir\> -dev


where \<gamedir\> is your mod folder containing your **liblist.gam** file.


[Here are a few enemies](https://github.com/malortie/halflife/tree/branch-malortie-op4/dlls/gearbox) I coded in an attempt to reimplement Op4 entities, so that you can see a few samples.


Hope it helps.

**Comment by headshoter** [comment]
@malortie 

well, i'm new with SDK and C++, but i'm doing a lot of things.

finding in russian websites , i found most of the Op4 npcs and weapons, most of it worked fine, but pitdrone it's crashing when they see a enemy.

if you want to see this files https://drive.google.com/folderview?id=0B6rw7JTgR9zPfkk1MHo4N3B2WG1CLWR2WGJjbFNCOGhMR2lIMURZTF9KOXFQeE14VEFad0E&usp=sharing

yes, i know about launching the game from VS, but my problem debugging it it's when the game crash, the debugger can't continue debugging (starts to get a lot of errors like:

Exception produced in 0x77CB75C5 (ntdll.dll) in hl.exe: 0xC0000005: Access violation writing location in 0x00030FFC.

)

and that's why i can't debug to see the problem.

**Comment by malortie** [comment]
The link you provided above does not allow me to see the files, you will need to permit file sharing. I will then proceed and take a look at them.

**Comment by headshoter** [comment]
oh, sorry.

you can see it now.

**Comment by malortie** [comment]
Here, I hightlighted the problem:

```cpp
//=========================================================
// CheckRangeAttack1
//=========================================================
BOOL CPitDrone::CheckRangeAttack1(float flDot, float flDist)
{
	if (!horns)
	{
		//RunAI(); // <-- PROBLEM:  Calls recursively RunAI.
		return FALSE;
	}

```

```cpp
void CPitDrone::RunAI(void)
{
	// first, do base class stuff
	CBaseMonster::RunAI(); // <-- Calls recursively RunAI.

	if (m_hEnemy != NULL && m_Activity == ACT_RUN)
	{
		// chasing enemy. Sprint for last bit
		if ((pev->origin - m_hEnemy->pev->origin).Length2D() < PITDRONE_SPRINT_DIST)
		{
			pev->framerate = 1.25;
		}
	}

}
```

Hope it helps.

**Comment by headshoter** [comment]
@malortie yeah, now it works.

maybe i can leave this open, still interested in debug my mod correctly.

**Comment by JoelTroch** [comment]
# Getting ready to debug #
The following screenshots were made in VS2013, it should be the same on VS2015.

First, make sure you have selected the "Debug" configuration like the screenshot:
![000_config](https://cloud.githubusercontent.com/assets/4483707/9495884/fa57c656-4c0d-11e5-9618-28579f84ee1b.png)

In the "Solution Explorer", the project in **bold** is the **"startup project"**, on the following screenshot, you can see that my **"server" project is the "startup project"**, this can be changed by right-clicking on a project and clicking on "Set as startup project".
![001_projects](https://cloud.githubusercontent.com/assets/4483707/9495937/38a1f256-4c0e-11e5-823e-424c135ee28f.png)

Now go that project's properties (right click, properties), go to the "Debugging" section and look at the screenshot below to see how to configure:
![002_debug](https://cloud.githubusercontent.com/assets/4483707/9495986/6fcb50ec-4c0e-11e5-8380-4fa8951cc281.png)

You just need to apply the settings and close the configuration window, **assuming you haven't changed the "Output directory" of the projects, before debugging, you will need to copy the DLLs, PDBs, LIKs, LIBs, EXPs files for both "client" and "server" projects into your mod folder**.

# Debugging with Visual Studio's debugger #
Press the "Play" button (or F5) to start debugging, you may have a warning that VS can't find the PDB for "hl.exe" and/or other files, just ignore and say "Yes".

# Debugging with WinDBG #
If for some reason you don't want to use VS's debugger, you can use WinDBG which is included within the Windows SDK. The Windows SDK is available for download at Microsoft's download center website for free, just download the one adapted to your Windows version (if you are using Windows 7, download the Windows 7 SDK. If you are using Windows 10, download the Windows 10 SDK).

Once you have installed the Windows SDK, start your mod like if you were playing it, once you have reached the main menu, start WinDBG (Start Menu -> Windows Kits -> WinDBG (x86)).
When WinDBG has started, press F6 or go to "File -> Attach to process", select the "hl.exe" process and click "OK", you will notice a new window in WinDBG and Half-Life is frozen, type "g" in that new window and press "Enter" to resume the debugging process.

**IMPORTANT NOTE:** Don't use the 64 bits of WinDBG, it won't work because Half-Life is a 32 bits application.

**Comment by malortie** [comment]
> @JoelTroch 
> you will need to copy the DLLs, PDBs, LIKs, LIBs, EXPs files for both "client" and "server" projects into your mod folder.

You can setup build events to automatically copy compiled files DLLs to your mod folders. To do so, open up both projects and proceed to the **Build Events** section.

In **Build Events**, find a sub-section named **Post-Build Event**. Append the following to **Command Line**:

---
### hl_cdll (The client)

**if exist $(TargetPath) copy $(TargetPath) "C:\Program Files (x86)\Steam\steamapps\common\Half-Life\YourModFolder\cl_dlls\$(TargetName).dll**

**if exist $(TargetDir)\$(TargetName).pdb copy $(TargetDir)\$(TargetName).pdb "C:\Program Files (x86)\Steam\steamapps\common\Half-Life\YourModFolder\cl_dlls\$(TargetName).pdb"**

---
Repeat the above for the server.

---
### hl_dll (The server)

**if exist $(TargetPath) copy $(TargetPath) "C:\Program Files (x86)\Steam\steamapps\common\Half-Life\YourModFolder\dlls\$(TargetName).dll**

**if exist $(TargetDir)\$(TargetName).pdb copy $(TargetDir)\$(TargetName).pdb "C:\Program Files (x86)\Steam\steamapps\common\Half-Life\YourModFolder\dlls\$(TargetName).pdb"**

**Comment by JoelTroch** [comment]
@malortie I know, but if you read again my post, you will see "assuming you haven't changed the "Output directory" of the projects".

**Comment by malortie** [comment]
Sorry, I have read your post too fast; a mistake of my own. Thanks for correcting me.

**Comment by headshoter** [comment]
oh thanks i can debug now.

thanks to everyone, you helped me a lot.

time to close it.
