### ISSUE TITLE
Counter Strike and Condition Zero Latency Problem

### ISSUE THREAD

**Issue by erdemtekin** [ValveSoftware/halflife#1700]
@alfred-valve @johnv-valve 

I have CS Anthology and HL Anthology on steam.But I could not play CS and CZ smoothly.

I have lag problem on online servers and I have lag problem on lan server.

My friend creates a server and I connect to his server.I can't play smoothly on his server.
When I create server he can't play smoothly.

"cl_lw 0" fixes lag problem but it isn't legal in tournaments and matches

I know it is a client problem.I can play smoothly in singleplayer (with bots)

I tried rate commands,disabling firewall,disabling DEP etc. but they didn't fix problem

Also,I am using vsync.When I set fps to 100, it doesn't fix problem.So,I must play in 60fps because I am using 60hz screen.

Here is my gameplay video:

Note:if you watch in fullscreen and 720p you can see lag.(When I jump and fire)
https://www.youtube.com/watch?v=3z3Cy4Ciexo

Note:I don't have lag problem like this on other games(CS Source,CS GO,BF etc.)

Please tell me a solution

**Comment by CloudHaze** [comment]
@erdemtekin I'm glad to see you here, I've see some post of you in the past about cs isn't smooth you are hero man, because you keep looking  to fix the problem, I think i've find a way to play cs  1.6 smooth
results that  in 1999-2005 most of the computers or gammers used  to run counter strike at (one core) 
Because their pc were configured to run Microsoft service pack 3 with cpu intel one core overclocked to 4.0 to 4.7 ghz handling very well xp and running 100%  good the cs 1.6 

But nowadays most of the computers like INTEL, AMD, has multi threading processor, and by shutdown games to run 1 processor like most people do is not good..

So i highly recommend if you are running a intel7 or amd with 8 cores
Try to unpark CPUCORES (search in Youtube)
Once you have unparked your cpu cores
Next STEP IS: 
If you have Nvidia, try to go to Nvidia Control panel , custom games half life
And find an option named (Threaded optimization) this will use all cpu cores for your cs 1.6
You will notice if you open console in menu game and type (stats) stats stats, continusly cpu will be around 150-170, if you set that Threaded optimization to auto or 0, it will be avg of 90-100
Which is not good... 

Another thing is to turn off power save features in BIOS and in Windows.... but threaded optimization has helped me alot , i still finding more ways to put my game more smooth, but right now i have a better rcoil and i always do 4k, 3k depends on server.

**Comment by erdemtekin** [comment]
@CloudHaze

**Comment by CloudHaze** [comment]
@erdemtekin but did you test what i told you about,cpu and things?

Also if you are running a monitor 60 hertz, if you want to avoid the fps screen tearing try to set fps to
You will try these fps in order to avoid screen tearing in (60 hertz monitor okay)
1- fps_max 70 , play 2 minutes check if there are any screentearing
2- fps_max 72, play 2 minutes check if there any screentearing
3- fps_max 75, play again another 2-3 minutes check if there any screentearing
4- fps_max 80, test over 2 minutes by running, jumping etc
5- fps_max 90, test again 2 minutes
6- fps_max 120, lastly test this by running to see if there any screen tearing

erdemtekin another thing with input lag i will recommend you to
Test m_rawinput 1 cl_mousegrab 0, and mouse polling rate set to 125 hertz, to see if you feel more smooth 
if you have steam we can talk more often.
Also if you can record a (demo.dem) and upload to mediafire and share with me ill check
also make more videos for youtube.

**Comment by erdemtekin** [comment]
@CloudHaze Yes I unparked cores and I adjust threaded optimization.

I downloaded CS 1.6 Warzone Final.And it is BETTER than CS Steam version.Because I can play more smooth in this version.I don't know why I can play more smooth on this version.İt is better but it isn't best...
Warzone Final's build version is 4554.But I want 6153 because it has HD Models and it supports HD resolutions.

I looked Warzone/cstrike/config.cfg,userconfig.cfg,listenserver.cfg and server.cfg.
Their rate and other command values different from CS Steam's files

I am thinking now : this issue stems from netcode

Or it helps only...

I sent friend invite to you.

**Comment by CloudHaze** [comment]
Hello sir Erdemtekin, did you send the invitation to my id steam yura10?
because it didn't come :( i cant see your friendship
And by the way, whats that cs 1.6 Warzone Final? :O? does is like non steam
counter strike?

oh i want to download that cs 1.6 warzone in order to test de game
Whats your steam id or nickname to add you.

**Comment by CloudHaze** [comment]
And by the way what version should i dowload from Cs  1.6 Warzone the 4554?
or the 6153? did you downloaded the 4554?

**Comment by erdemtekin** [comment]
@CloudHaze
Hi!
 I want download Warzone 6153 but there is no 6153.
Only 4554 :(

**I downloaded 4554.it is smoother than steam version(6153) but steam version has more features(HD resolutions,HD models etc.) **

Warzone is nonsteam cs.

My steam id: charlesbronson741

**Comment by CloudHaze** [comment]
I  added to my friendlist Im haze, by the way i did try the 4554 it feels
way smooth, but i dont know it ha some issues with (console) it close
automatically when trying to add cvars.. and yeah the  cs 1.6 non steam has
differents files than the steam..... o.o

**Comment by erdemtekin** [comment]
@CloudHaze because it is 2009 build of Counter Strike and it is old.

Finally,Steam should update the game ;)

**Comment by erdemtekin** [comment]
Bump

**Comment by ViBE-HU** [comment]
you should ping a bit some favourite servers and check the pocket loss. i know that you have only problems with 1.6 but it can be just some network problems with some hosts/servers. net_graph 2 can be useful too.

**Comment by erdemtekin** [comment]
@ViBE-HU 
I used net_graph 2 before.

This lag problem appears on all online servers and LAN server.

Just singleplayer(with bots) smooth.

**Comment by djdallmann** [comment]
This is most likely caused by this update:
"Improved firing behavior in Counter-Strike, Counter-Strike:Condition Zero and Half-Life Deathmatch, it is no longer dependant on client or server frame rate. This change needs both your client and server updates to see the improvements. "

**Comment by erdemtekin** [comment]
@djdallmann Same in older versions(6132,4554 etc.)
