### ISSUE TITLE
[Request] Make sv_cheats work in realtime

### ISSUE THREAD

**Issue by Solokiller** [ValveSoftware/halflife#1758]
sv_cheats currently does not work in realtime. If you change it, you must change the map or restart the server in order to use cheats. Making it use the value in realtime would allow for cheats to be used after changing the setting, or preventing cheats after disabling it.

**Comment by 2010kohtep** [comment]
I would like to try to propose a solution for this problem.

The problem itself is that the client does not check the value of ```sv_cheats``` explicitly (which could be changed using the stufftext request), but uses the variable inside the engine - ```qboolean allow_cheats;``` for this. This is done so that the client cannot use cheat commands if they are prohibited on the server. This variable is used on both sides: the server sets it at startup (function ```SV_SpawnServer```), and the client - when connected to the server. However, if the server changes the value of ```sv_cheats```, then the value of ```allow_cheats``` will remain the same and will not be changed until the server restarts or changes the map.

If the structure of console variables had a callback system, I would suggest adding one to check ```sv_cheats``` for changing and sending clients a new ```allow_cheats``` value, but a similar system is implemented only in the Source engine, so we need a different solution here.

I see the following one. The game engine contains the function ```SV_QueryMovevarsChanged```, which sends the modified values of the console variables that are responsible for the physics and skybox settings. Sending occurs if at least some variable has been changed on the server. I think that the best solution for the current engine architecture is to create a similar functionality for ```sv_cheats```, which would be located next to ```SV_QueryMovevarsChanged``` and which would send ```svc_sendextrainfo``` message to all clients that contains the new value of this console variable.

However, this is only part of the solution, since the gamedll also performs checks on the activity of the cheat mode when working with impulse commands. It's in function ```CWorld::Spawn```, which contains the following code:

```
g_flWeaponCheat = CVAR_GET_FLOAT("sv_cheats");
```

I believe that ```float g_flWeaponCheat;``` should be replaced by ```cvar_t *sv_cheats```, and the code itself should be as follows:

```
sv_cheats = CVAR_GET_POINTER("sv_cheats");
```

After that, of course, it will be necessary to change the existing code where the variable ```g_flWeaponCheat``` was earlier.

@mikela-valve, it seems to me that this is a fairly simple solution and given the fact that this sv_cheats problem is very irritable, many would be grateful for fixing it.

**Comment by Solokiller** [comment]
This was implemented in one of the updates a couple years ago. Once the SDK has been updated with the changes it should be all good. I'm closing this issue as per other similar changes also having their issues closed.
