### ISSUE TITLE
Temporary disable an entity's Use() ...?

### ISSUE THREAD

**Issue by johnstt** [ValveSoftware/halflife#1780]
I'm trying to figure out a way to temporary disable the use() ability of entities. 
I want something that will work for any entity as a one-liner. Doors, buttons, etc etc...

I've thought of a couple ways but haven't got anything working yet:
- Setting a flag on the entity's pev (which flag? where do I want to check it to prevent using?)
- Temporarily setting the use function null (is there a generic way to get the use function and memorize it before setting it null?)

Any ideas would be appreciated!

**Comment by SamVanheer** [comment]
There is no built-in way to do this, you'll have to implement it yourself. If it's only player +use you can add a delay member to CBaseEntity and check it in the player's +use code, then set it to the time you want to enable it again. 

Otherwise you'll have to rework the codebase, since a lot of entities override Use() and thus forces you to handle it in every overridden method.

**Comment by johnstt** [comment]
I bet this is super easy in xash3d right? hahahha

In any case, thanks for the help.

**Comment by tschumann** [comment]
I'm not fully sure on how the Use code works but could you not add a check in DispatchUse?

**Comment by SamVanheer** [comment]
The Use code is implemented in the server library, but not all users call DispatchUse, some call Use directly. There is no easy way to rework it with a built-in delay.
