### ISSUE TITLE
One minutes remaining in C.S. 1.6

### ISSUE THREAD

**Issue by jack17529** [ValveSoftware/halflife#1783]
Very funny but in your some file C.S. 1.6 when the time , only 1 minute is left , it said "only one minutes remaining " , it should be "only one minute remaining" .

**Comment by jack17529** [comment]
Please tell me the file and assign the issue.

**Comment by AtiPLS** [comment]
It's probably some amxmodx plugin that says that (i'm assuming) and it doesnt have a "minute" sound only "minutes"

That's probably the issue and can be fixed by adding a "minute" sound

**Comment by jack17529** [comment]
@AtiPLS please send me link of the file .

**Comment by nurupo** [comment]
It's not something that is easily fixable. Audio files that come with hl don't have "minute" sound file, only "minutes". The time announcement you hear on CS servers is likely done by the `amxmodx` mod, which is installed on the server and it tells all connected to the server players to play `minutes.wav` file. This means that even if you create your own `minute.wav` file

1. You would have to make the server you play on to use the `amxmodx` mod patched to tell players to play `minute.wav` file in addition to the `minutes.wav`.
2. The other players would have to have the `minute.wav` sound file on their system, which is probably possible to achieve by having it as one of custom server sounds. But beware that HL games have an option in settings to disable downloading of custom server files, which is reasonable option given how many servers overuse visuals and sounds. This means that it's not guaranteed that `minute.wav` file would be downloaded by a player, and when the server asks the player's CS to play the sound, the player won't hear anything since there is no `minute.wav` sound file.

**Comment by nurupo** [comment]
Here is the relevant [`amxmodx` code part](https://github.com/alliedmodders/amxmodx/blob/e95099817b1383fe5d9c797f761017a862fa8a97/plugins/timeleft.sma#L124-L165), if you are curious.

As far as where you can get the `minutes.wav` file, the only legal way of getting it that I know would be buying CS 1.6 game, as it comes with the game. Now, even if you get the file `minutes.wav` with the CS 1.6 game, I don't think you are legally allowed to edit it.

**Comment by SamVanheer** [comment]
This is not a problem with the game itself, just a plugin that uses the same sound. This issue can be closed.

**Comment by kisak-valve** [comment]
Closing per the last comment.
