### ISSUE TITLE
Half life 1 Server Doesen't Download fully.

### ISSUE THREAD

**Issue by shytzedaka** [ValveSoftware/halflife#1835]
I have been Countering this issue for months. and im sure many people have with CS 1.6 And other Gold source based games.  Where if you try to download The Server files for Half life (App id 90) it Does not download all of the files. it may say it did but it doesn't I'd like To know if there is any way to fix this?

**Comment by djdallmann** [comment]
No fix for this to my knowledge :(, if you are providing game server services it might be best to download it once properly then use that as a base for your deployments.

**Comment by shytzedaka** [comment]
I See.

**Comment by BlyteScrin** [comment]
When downloading with steamcmd.exe the valve folder only has the dll folder and file.  if you run steamcmd.exe again it returns with the following  instead of downloading the cstrike folder as it usually does on the 2nd run.
----------------
Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
force_install_dir C:\HLDS\half-life\AAOzserver002
app_update 90 validate
 Update state (0x5) validating, progress: 0.00 (0 / 39011709)
 Update state (0x5) validating, progress: 78.22 (30515461 / 39011709)
Success! App '90' fully installed.
quit
CWorkThreadPool::~CWorkThreadPool: work processing queue not empty: 1 items discarded.
-------------------
If you download hlds with the steam browser / tools it downloads .all the base files and the full valve and cstrike folders to your game client. It never asks for the directory location to download hlds to.

The server will only run using the hlds.exe GUI as localhost even though the GUI shows it is set for internet.  It will run when using the console, but it stops when trying to connect with steamauth .  The console reports the ip as localhost .  If I add the host ip and port to the command-line the server opens then closes immediately.  I have even tried it without a router or firewall and got the same results.

**Comment by rx1983** [comment]
I have a similar problem.
https://forums.alliedmods.net/showthread.php?t=304005
