### ISSUE TITLE
Server with SlowHacking

### ISSUE THREAD

**Issue by Soyrce** [ValveSoftware/halflife#1884]
hey im playing on Some server and the admin use Slowhacking on me.

change my fps_max 
and make me to reeconnect..

how can i block it from STEAM?

**Comment by hashnimmo** [comment]
As far as I know, an AMXX plugin is responsible for this. Those admins are abusing a useful function that can be used for good purposes. If I were you, I wouldn't play on that server ever again. Seems like you will need to re-install the game now after fully removing those old game files. Make sure to set your whole game folder to read-only after you made necessary changes to your new game settings.

**Comment by hashnimmo** [comment]
Recently found out that you can't avoid this even though your files are read-only. Not sure about that though.

**Comment by Soyrce** [comment]
my files already read-only for a year+, but the server im playing still can use any client_cmd on me..

**Comment by SamVanheer** [comment]
There's an exploit that can be used to execute any command: https://github.com/ValveSoftware/halflife/issues/1497

No fix for that yet though, will have to wait and see if Valve gets around to it.

**Comment by SamVanheer** [comment]
That only affects `svc_stufftext`; the exploit i was referring to above bypasses that.

**Comment by BlackShadow306** [comment]
Sadly you can block them, they're using raiz0's fake server hoster. All they doing is uploading a php script to hosting sites and host more than fake servers on server list. When you try to connect their servers, they redirecting you to a server and server is slowhacking your game. And yes AMXX is responsible for this. I used to use one of those config (I have to) to modify their rate and fps_max commands in order to get them best ping on my server. Even the purpose seems usefull its still evil. As far i know even Valve can't do anything about AMXX slowhacking.

**Comment by BlackShadow306** [comment]
Sadly you can't block them, they're using raiz0's fake server hoster. All they doing is uploading a php script to hosting sites and host more than fake servers on server list. When you try to connect their servers, they redirecting you to a server and server is slowhacking your game. And yes AMXX is responsible for this. I used to use one of those config (I have to) to modify their rate and fps_max commands in order to get them best ping on my server. Even the purpose seems usefull its still evil. As far i know even Valve can't do anything about AMXX slowhacking.

**Comment by BlackShadow306** [comment]
Sadly you can't block them, they're using raiz0's fake server hoster. All they doing is uploading a php script to hosting sites and hosting fake servers on server list. When you try to connect their servers, they just redirecting you to another server and that server is slowhacking your game. And yes AMXX is responsible for this. I used to use one of those slowhacking plugin in my server (I have to) to modify players rate and fps_max commands in order to get them best ping on my server. Even the purpose seems usefull its still evil. As far i know even Valve can't do anything about AMXX slowhacking.

**Comment by BlackShadow306** [comment]
Sadly you can't block them, they're using raiz0's fake server hoster. All they doing is uploading a php script to hosting sites and hosting fake servers on server list. When you try to connect their servers, they just redirecting you to another server and that server is slowhacking your game. And yes AMXX is responsible for this. I used to use one of those slowhacking plugin in my server (I have to) to modify players rate and fps_max commands in order to get them best ping on my server. Even the purpose seems useful its still evil. As far i know even Valve can't do anything about AMXX slowhacking.

**Comment by APGRoboCop** [comment]
I suspect they use some kind of execall command AMXX plugin or something...

**Comment by Soyrce** [comment]
so i just stopped to get into to this server?

**Comment by Maxi605** [comment]
@alfred-valve this is fixed.

**Comment by kisak-valve** [comment]
Closing per the last comment.
