### ISSUE TITLE
GoldSrc games cannot do 640x480

### ISSUE THREAD

**Issue by kisak-valve** [ValveSoftware/halflife#1908]
Issue transferred from https://github.com/ValveSoftware/steam-for-linux/issues/5799.
@shoober420 posted on 2018-09-29T03:05:20:

* Steam client version (build number or date): Sep 26 2018
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

1. Try to set 640x480 for GoldSrc games

[System Information (Steam)](https://gist.github.com/shoober420/1215c40214cf70e1fabb760b5bd2a341)

***
@shoober420 commented on 2018-09-29T15:02:06

The lowest resolution it can do is 800x600. I personally play all GoldSrc games when competitive, at 640x480

**Comment by shoober420** [comment]
When adding the "-width 640" and "-height 480" launch options to CS1.6, the game launches in "720x400 Widescreen" mode. GoldSrc no longer sees 640x480 as a vadlid resolution. I have 640x480 mode added to xorg via my .xinitrc file as such.

xrandr --newmode "640x480_170.00"   78.25  640 688 752 864  480 483 487 533 -hsync +vsync
xrandr --addmode DVI-I-0 640x480_170.00

CS1.6 saw the resolution when this was added, but no longer. CS1.6 only will see 800x600 as the lowest possible 4:3 resolution.

**Comment by SamVanheer** [comment]
The engine gets the list of valid resolutions from the operating system through SDL. If SDL is not reporting those as valid resolutions it will take the nearest valid resolution.

However, you can try using the command line option `-forceres`. This may let you force a resolution to be used even if it wasn't reported as valid.

**Comment by shoober420** [comment]
That command line parameter had no effect. That parameter is not listed on https://developer.valvesoftware.com/wiki/Command_Line_Options, where did you find it?

**Comment by SamVanheer** [comment]
I reverse engineered the engine to see if there was anything that could override it.

Try using the console command `_set_vid_level` with the argument `0`. This should also be accessible in the options menu tab `Video` as the low video quality option. It should be unchecked to match the value.

This should make it use the resolution specified with `-width` and `-height`. Note that if you also specify `-w` and `-h` it will override the values for width and height, respectively.

**Comment by shoober420** [comment]
Sorry, for the late response. Alot has been going on. So i just loaded up the game and did some debugging. I got some good information.

The game will definitely not do 640x480 when -nofbo is launched. The game will refuse to go fullscreen, and is stuck on that 720x400 widescreen resolution.

BUT, when playing without the -nofbo resolution, the game does go fullscreen, but theres no guarantee its really 640x480 since you probably know @SamVanheer , using -nofbo allows the game to be upscaled and downscaled. I did play with the -nomsaa option, which should technically be identical to playing with -nofbo, but I cant confirm this, Im not a programmer, soi cant dig into the code, and no documentation fully details what the new FBO render does and is capable of.

Regardless, playing the game without using the -nofbo launch parameter does seem like it allows 640x480, but again, this isnt 100% factual as of right now. Im going to create another issue about CS1.6 not being able to launch fullscreen 640x480 while using the -nofbo option, and this will further confirm if its true 640x480. I will close this for now though.

**Comment by shoober420** [comment]
Nevermind, its already been closed lolol, and cant seem to be reopened. Alrighty then.

**Comment by shoober420** [comment]
I thought I would mention here, that if you start GoldSrc games without the “-nofbo” launch parameter, the game claims 640x480 under the video tab in the options menu. This may as well be clarification that true 640x480 resolution is being used.

**Comment by shoober420** [comment]
Also, using the “-forceres” launch parameter is required for 640x480 to work when playing without the “-nofbo” launch parameter.

Thanks for the tip @SamVanheer
