### ISSUE TITLE
Last update broke Deathmatch Classic

### ISSUE THREAD

**Issue by basuritashka** [ValveSoftware/halflife#2109]
From Reddit: /u/agitationskeleton: Particles and projectiles such as nails and explosions do not appear, and firing sounds and other weapon sounds do not play.

Looks like Natural Selection got broken aswell. :)

**Comment by SamVanheer** [comment]
It looks like this happens because the function `IsSafeFileToDownload` has incorrect logic.

The function is designed to positively verify that a file is safe to download. It does this by checking if the extension is NOT one of a given set of extensions, among other things.

The problem is that before it checks the extension, it checks to see how long the extension is, in bytes. This includes the dot.

All extensions must be 4 bytes long (dot + 3 bytes). This means common extensions like `.mdl` and `.spr` work.

The problem is that a file can only be deemed safe if it passes this check. The `.sc` extension is only 3 bytes long, so it never passes the check.

This problem can be verified by looking in the console for errors like this: `Invalid file type...skipping download of events/powerup.sc`

This is verified to happen with mods as well: https://twhl.info/thread/view/19707

Strangely not all games are affected. Half-Life works fine and plays events (seen with `cl_showevents 1`). No errors are visible in the console.

It is important to note that the code in this function was like this before the update as well.

The reason why it now causes problems is because the use in `CL_BatchResourceRequest` was moved out of a switch statement to occur prior to that switch.

Previously, event resources (type 5, `t_eventscript`) were not subject to this check.

I recommend amending the code in `IsSafeFileToDownload` to properly handle extensions of any length. It may also be worth updating the checks to actually check for the extension (i.e. `!Q_stricmp( pszExtension, ".exe"` and so forth), and not the occurrence of the string anywhere in the filename (`!Q_stristr(lwrfilename, ".exe")`).

**Comment by SamVanheer** [comment]
This bug has been fixed. The engine now correctly checks all extensions without the byte length check. Update your game installation to get the fix.
