### ISSUE TITLE
Update SDK Code

### ISSUE THREAD

**Issue by SamVanheer** [ValveSoftware/halflife#2110]
The latest update added a new engine function to the client:
`pfnEngSrc_pfnFilteredClientCmd_t pfnFilteredClientCmd;`

Please add it to the SDK along with other missing changes.

**Comment by basuritashka** [comment]
Source? I would like to know where are you looking to find that info.

**Comment by SamVanheer** [comment]
I reverse engineered the Counter-Strike client.dll to see how they fixed the Director Message exploit.

**Comment by basuritashka** [comment]
Do you mind sharing the content from "pfnEngSrc_pfnFilteredClientCmd_t pfnFilteredClientCmd;"?

**Comment by SamVanheer** [comment]
`typedef int (*pfnEngSrc_pfnFilteredClientCmd_t)(char *);`

It has been added to the end of the engine functions interface.

**Comment by tschumann** [comment]
Thanks - it goes right after pfnVguiWrap2_GetMouseDelta?
And what are the other missing changes?

**Comment by SamVanheer** [comment]
Yeah it's at the very end so the interface isn't broken for existing games.

Other changes include missing flags to indicate if a cvar is a privileged or `cl_filterstuffcmd` privileged command, missing bug fixes like the weapon select server crash exploit, possibly others that haven't been merged in.

**Comment by mikela-valve** [comment]
Hi @SamVanheer, I'm going to co-opt this issue into being a general tracker for getting the SDK updated to include all changes to it that I can find since the last commit in 2014. I may just break it up into several commits as I have time to audit files and include them in the update so I'll make notes here when I update files.

**Comment by SamVanheer** [comment]
Alright, see also:
#2101
#1839

**Comment by mikela-valve** [comment]
Thanks, I’ll close out #2101 first and close #1839 in favour of this one. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SamVanheer** [comment]
If possible, can support for using VGUI2 be added to the SDK? Mods can use it but the VGUI2 controls library and required interfaces are missing so everything would need to be reverse engineered or adapted from Source.

See #1639 and #1739

A template for making a VGUI2 based HUD like Counter-Strike would be nice to have, since it's still a lot of work otherwise.

**Comment by Solokiller** [comment]
I've been updating a copy of the SDK to include all of the changes that have been made so far: https://github.com/Solokiller/halflife-updated

I've gone through the list of bugs listed in the milestones to make sure each fix has been applied. Additionally there are also fixes that have not yet been applied to the official games.

The fix for #1377 is temporary pending a full fix with engine-level support. The code that is currently in my version of the SDK exists in the engine but is not used for reasons explained in the issue.

**Comment by coderamen666** [comment]
Can you merge all the November 2023 changes to the sdk so that modders have corresponding source code to the 25th anniversary release?

**Comment by SamVanheer** [comment]
@shawns-valve since all changes seem to have been merged this issue can probably be closed, unless there are plans to include VGUI2 or other functionality in the SDK as well?

**Comment by kisak-valve** [comment]
Closing per the last comment.
