### ISSUE TITLE
[Question] Open GoldSource Source Code.

### ISSUE THREAD

**Issue by tyabus** [ValveSoftware/halflife#2125]
Goldsource engine is 22 years old now, i think it's the time for opening source code, isn't it?

**Comment by JoelTroch** [comment]
Duplicate of #1712

**Comment by sabianroberts** [comment]
@tyabus I doubt Valve think it's safe; GoldSource still has a very active online playerbase with CS 1.6 and Half-Life, and opening the source would leak exploits in VAC and SteamPipe that would cause an increase in cheaters and hackers, especially in Counter-Strike. The same would happen to Source games, since Source is a modification based on GoldSource.
