### ISSUE TITLE
After upgrade to beta (8212), textures are pixelated

### ISSUE THREAD

**Issue by GiovaniFerraroTrivelli** [ValveSoftware/halflife#2148]
![usd7pq0](https://user-images.githubusercontent.com/27016185/56452594-a9225b00-6308-11e9-9d0a-9cd10007b516.jpg)

**Comment by mikela-valve** [comment]
That is currently intentional. With 8212 I enabled support for the native texture dimensions if your graphics card supports them (which most everything does today) and disabled texture filtering. This is intended to make textures look as sharp and detailed as they do when running with the software renderer.

If you don't like this as the default, you can use 'gl_texturemode GL_LINEAR' to re-enable filtering. We are using issue #1650 to track this so please leave any comments or criticisms there.
