### ISSUE TITLE
Writing files from server when cl_allowdownload 0

### ISSUE THREAD

**Issue by Splatt581** [ValveSoftware/halflife#2220]
As I understand it, the client cvar `cl_allowdownload` is responsible for saving files received from the server. It performs its function when the client receives a list of cached resources from server and does not send a command to download the missing files, if cvar is set to 0. But if the server itself starts sending files, they will be saved in the client's file system, regardless of `cl_allowdownload 0`. It seems that need to add an additional check with this cvar in `Netchan_CopyFileFragments` before writing the file.

**Comment by mikela-valve** [comment]
Fixed, this will be included in the next beta update.

**Comment by mikela-valve** [comment]
Fixed in 'Exe build: 11:11:14 May 21 2019 (8244)'.

**Comment by Splatt581** [comment]
I confirm, fixed.

**Comment by Splatt581** [comment]
I noticed a problem that appeared after this fix - now if the client uploads its logo to the server, then the server will reject it in any case due to a new check:

`File fragment received but cl_allow_download set to 0, ignoring`

**Comment by mikela-valve** [comment]
@Splatt581 Just to check, were testing this on something other than Windows? I think this is another case of the Windows and macOS/Linux server binaries being compiled differently, as that cl_allow_downloads check is already not compiled into HLDS but is there on macOS/Linux due to the engine being shared between the client and server.

I'll add a check for `cls.state == ca_dedicated` to keep it from running this. I think this check will also fail for a client running a listen server so I'll also suppress it if the max clients are `>1`.

**Comment by mikela-valve** [comment]
This should be fixed in beta update '15:46:27 Jun 11 2019 (8265)'.

**Comment by Splatt581** [comment]
@mikela-valve No, tests were performed only on Windows binaries. I can confirm that it was fixed in last beta and now uploading of logos works correctly for dedicated and listen servers on Windows.
