### ISSUE TITLE
The '_setgamedir' command allows to set gamedir outside the application folder

### ISSUE THREAD

**Issue by Splatt581** [ValveSoftware/halflife#2221]
For example, by executing the following string `_setgamedir ../;_restart`. This may allow some files to be written outside the base directory of the application. Perhaps it is worth adding a check for the substring `..`, and when it is found, set the default gamedir `valve`.

**Comment by SamVanheer** [comment]
When this is done, doesn't the engine fall back to loading the vanilla Half-Life client.dll? That would prevent any malicious code from being run that uses the engine filesystem (not that this matters since you can just use fopen/fstream/etc to do this directly).

Without a `liblist.gam` file to tell it which server dll to load you can't host servers, so that leaves only connecting to servers that can then upload files to the chosen directory.

I tried to connect to a Counter-Strike server from Opposing Force (gearbox to cstrike). I got this message:
`Server is running game cstrike.  Restart in that game to connect.`

I checked the engine and it looks like this is an optional check in `CL_ParseServerInfo`, although the current logic will cause it to never run the alternate code, which prints this:
`Server didn't specify a gamedir, assuming no change`

This happens very early in the connection phase, however code related to player customization (sprays) runs before this check occurs.
This might result in files being downloaded and created on disk before the check disconnects you.

Combined, you could do `_setgamedir ../;_restart; connect <ip>` and download files to a directory located [anywhere on the same hard drive](https://social.technet.microsoft.com/Forums/lync/en-US/eebbcbf3-7aab-45b9-8d2a-63c94a3ce1e8/relative-path-of-a-folder?forum=ITCG), provided the process has the privileges to do so.

I also found that one server i tried to connect to thought i was running a No-Steam game and disconnected me, this looks to be a plugin of some sort. I thought it was worth mentioning.

All that aside, the game directory probably shouldn't contain `..` or any path separators of any kind (`/` and `\` at the very least) to prevent other problems.

**Comment by mikela-valve** [comment]
I agree, this command should undergo the same validation that other commands that take a directory as a parameter perform.

**Comment by mikela-valve** [comment]
I'm going to add the same checks that `motd` and other commands have which disallow any path characters that allow pathing above the base directory (leading '/', ':', '..', and '\') but if someone wants to set a game dir inside of another directory in the base directory with '/' that's probably fine.

**Comment by mikela-valve** [comment]
Fixed, this will be included in the next beta update.

**Comment by mikela-valve** [comment]
Fixed in 'Exe build: 11:11:14 May 21 2019 (8244)'.

**Comment by Splatt581** [comment]
I confirm, fixed.
