### ISSUE TITLE
'crcclientdll' key in liblist.gam does not work

### ISSUE THREAD

**Issue by Splatt581** [ValveSoftware/halflife#2225]
This key is used to verify the client library with the one located at the server, according to the crc hash. If there is a mismatch, the server should kick the client, but this does not happen. It seems that this mechanism does not work correctly. Also worth considering that need to check libraries on other operating systems, except Windows - `cl_dlls/client.so` and `cl_dlls/client.dylib`.

**Comment by SamVanheer** [comment]
Also note that the CRC check is enabled using a `liblist.gam` setting. Clients can simply disable this to disable any client side client dll verification. This is used to detect outdated clients and servers, and displays `Your .dll [%s] differs from the server's.`.

I'm not sure if there is a way to 100% detect modified clients from inside the engine, since you could modify the engine as well to disable client side checks, and send a valid CRC for the server to compare.

VAC should detect modified dlls, but as far as i know this only works for official games on VAC secured servers.

**Comment by LucesEnBabel** [comment]
> VAC should detect modified dlls, but as far as i know this only works for official games on VAC secured servers.

AFAIK it doesn't, it's common to see players swapping HL's Client DLL with Adrenaline Gamer's for example. (because they are compatible) Besides there are projects like OpenAG and Half-Life Bugfixed.

IMHO it should be up to the server operator to allow custom client DLL's, since VAC-banning seems a bit extreme and may cause people to use pirated clients instead.

**Comment by Splatt581** [comment]
Well, now I understand how it works. For this mechanism to work properly, it is necessary that the 'crcclientdll' key be sets on both the client and the server — the server to send the library hash to the client, and the client to verify the received hash. The hash is transferred to the `svc_serverinfo` message in a 16-byte field and in order to also verify clients on linux and osx, we will need to expand the protocol by adding new fields to `svc_serverinfo`, which will lead to serious backward incompatibility. I think while it is possible to close this issue.

**Comment by 0Ky** [comment]
> Replying to https://github.com/ValveSoftware/halflife/issues/2225#issuecomment-485482725

> VAC should detect modified dlls, but as far as i know this only works for official games on VAC secured servers.

@SamVanheer Unfortunately, this is not correct and I'm certain you're already aware of it. In the Half-Life community, it is widely known that players compile their own `client.dll` with additional custom ~~cheats~~ features implemented or download pre-compiled `client.dll` with prebuilt ~~cheats~~ features provided by the author of an open-source project only to replace the official game client. This appears to be something that's been ongoing for probably a couple of decades now and I don't think there has been a single instance of someone being VAC banned for replacing the `client.dll` and connecting to an official VAC secured server. This is currently affecting Half-Life 1 and other mods based on the GoldSrc engine, most notably Counter-Strike 1.6.

> I'm not sure if there is a way to 100% detect modified clients from inside the engine, since you could modify the engine as well to disable client side checks, and send a valid CRC for the server to compare.

You've pretty much described the issue, there isn't a way to `100% detect modified clients`, VAC doesn't and Half-Life Dedicated Server (HLDS) owners cannot. I would love to hear from @mikela-valve or @shawns-valve, is there a technical limitation and whether anything could be done, this is a serious matter as modified clients could contain cheats ~~features~~ like seeing players through solid walls and many more without any consequences what so ever, even though it directly violates the [VAC policy](https://help.steampowered.com/en/faqs/view/571A-97DA-70E9-FF74) and the [Steam Subscriber Agreement](https://store.steampowered.com/subscriber_agreement/):

### Valve Anti-Cheat (VAC) System
> Any third-party modifications to a game designed to give one player an advantage over another is classified as a cheat or hack and will trigger a VAC ban. This includes <ins>**modifications**</ins> to a game's core executable files and <ins>**dynamic link libraries**</ins>. 

### STEAM® SUBSCRIBER AGREEMENT
> G. Restrictions on Use of Content and Services
> ...you may not, in whole or in part, copy, photocopy, reproduce, publish, distribute, translate, reverse engineer, derive source code from, <ins>**modify**</ins>, disassemble, decompile, create derivative works based on, or remove any proprietary notices or labels from the Content and Services or any software accessed via Steam without the prior consent, in writing, of Valve.
>
> B. Cheating
>
> Steam and the Content and Services may include functionality designed to identify software or hardware processes or <ins>**functionality**</ins> that may give a player an <ins>**unfair competitive advantage**</ins> when playing multiplayer versions of any Content and Services or modifications of Content and Services ("Cheats"). You agree that you will not create Cheats or assist third parties in any way to create or use Cheats. You agree that you will not directly or indirectly disable, circumvent, or otherwise interfere with the operation of software designed to prevent or report the use of Cheats.

**Comment by di57inct** [comment]
ReChecker maybe? i know the client can send a fake crc check but i doubt a lot of cheats cover that.

**Comment by 0Ky** [comment]
Running a 3rd party Metamod plugin isn't a solution, it also does not `100% detect modified clients`. It doesn't even require any technical knowledge to bypass detection by ReChecker, since the server only requests the client to send the CRC checksum of the file on connect and never verifies what the client is actually running in memory.
