### ISSUE TITLE
gl_overbright & OpenGL

### ISSUE THREAD

**Issue by BUXPb** [ValveSoftware/halflife#230]
![1](https://f.cloud.github.com/assets/3612803/163972/a55a37da-7869-11e2-969a-f25e6fff0658.PNG)

![2](https://f.cloud.github.com/assets/3612803/163973/b3e8d82e-7869-11e2-976f-92b02129b75c.PNG)

gl_overbright only works in the Software and D3D, but only the latter was playable. Now, when he was removed from the Half-Life, there are no way to return gl_overbright through OpenGL c its new features? All the same, this mode is more pleasant to the eye. Thanks in advance.

**Comment by SamVanheer** [comment]
@mikela-valve What do the comments say exactly? I was able to get overbright to work (albeit using GLSL shaders) so perhaps things have changed since Alfred last looked into this.

Here are some screenshots showing the difference (off/on):
https://i.imgur.com/XJfTNqu.png
https://i.imgur.com/vwHxwvw.png

https://i.imgur.com/hNtoi4P.png
https://i.imgur.com/L6UOgQn.png

https://i.imgur.com/z0mlbmv.png
https://i.imgur.com/bDu21DC.png

https://i.imgur.com/DqOZPIe.png
https://i.imgur.com/rJVP19D.png

https://i.imgur.com/zFjbig0.png
https://i.imgur.com/PxcRaLq.png

**Comment by SamVanheer** [comment]
@mikela-valve @kisak-valve can this issue be reopened to track gl_overbright support?

**Comment by MFKitten** [comment]
Apologies for opening a new issue, I couldn't find this one. 

Overbright and detail textures can't be used together, and it would be very nice if they could be. If anything can be done to let them co-exist, that would open some doors.

**Comment by SamVanheer** [comment]
I patched the latest public build of the engine to ignore the `gl_texsort` check in `R_BuildLightMap`.

I don't see any problems with both detail textures and overbright being enabled at the same time. It works just like you'd expect, no glitches or anything.

If you need to test this out, here are keybinds i made to make this easy:
```
alias toggle_details_off "r_detailtextures 0; say DETAIL TEXTURES OFF; alias toggle_details toggle_details_on"
alias toggle_details_on "r_detailtextures 1; say DETAIL TEXTURES ON; alias toggle_details toggle_details_off"
alias toggle_details toggle_details_off
bind c toggle_details

alias toggle_overbright_off "gl_overbright 0; say OVERBRIGHT OFF; alias toggle_overbright toggle_overbright_on"
alias toggle_overbright_on "gl_overbright 1; say OVERBRIGHT ON; alias toggle_overbright toggle_overbright_off"
alias toggle_overbright toggle_overbright_off
bind v toggle_overbright
```

Overbright changes take effect when the lightmap is changed, so turn on the flashlight and shine it to see the changes, or reload the map. It's easy to see changes by turning on the flashlight, then toggling the features to see the difference. Condition Zero has a lot of maps that can be tested this way.

**Comment by MFKitten** [comment]
@SamVanheer that's fantastic news, and I haven't seen anyone reference this fact anywhere online yet. Is this literally in the game already, or do I need to enable this fix somehow?

**Comment by SamVanheer** [comment]
I patched the hw dll but it's not something that can be released. I basically replaced the jz instruction with 2 no-op instructions.

**Comment by MFKitten** [comment]
@mikela-valve this seems to be an "easy" fix, and it's easily as important as the non-PO2 texture rescaling fix.

**Comment by SamVanheer** [comment]
I'll reserve judgment until after we know what the comments say.

**Comment by MFKitten** [comment]
@SamVanheer going back and reading above, "not supported" is an interesting statement indeed. Non-po2 textures weren't supported either though really.

**Comment by kisak-valve** [comment]
Hello @SamVanheer, checking over this, Alfred made a fairly clear decision with this issue report back in 2013, and #1891 is open as a newer iteration of this request.

Friendly reminder that I'm a moderator for Valve's issue trackers on Github and not a Valve dev working on these games. If @mikela-valve wants to use this issue report instead of #1891, we can close that one in favor of re-opening this one, but beyond that I'm not inclined to re-open this issue report without an preference from a dev.

**Comment by MFKitten** [comment]
@kisak-valve is it possible to simply allow Sam's modification to go unchecked by VAC somehow, so modders can do it without getting VAC banned? That way nobody at Valve has to re-engineer or otherwise alter the engine, but the changes can be done without risk from the players.

**Comment by SamVanheer** [comment]
@kisak-valve Thanks for the reply.

@MFKitten I essentially hex edited the engine binary, that's not a solution. Mike still needs to look into it to see if it works properly and he can allow overbright to function easily by changing the code. My changes are useful only for local testing purposes.
