### ISSUE TITLE
MP3 playback thread makes non-threadsafe console print calls

### ISSUE THREAD

**Issue by SamVanheer** [ValveSoftware/halflife#2310]
The MP3 playback thread makes non-threadsafe console print calls that could result in the VGUI2 console text buffer leaking memory or being corrupted.

For example, `CCDAudio::MP3_InitStream` makes this call:
`Con_DPrintf("MP3_InitStream(%d, %s) successful\n", trackNum, g_pszMP3trackFileMap[trackNum]);`

This eventually goes into gameui.dll to append the text. At no point is synchronization performed to prevent the console buffer from being appended to by multiple threads.

If multiple print calls were to occur on both the main thread and this thread it could cause problems.

**Comment by mikela-valve** [comment]
I'm less inclined to fix this due to it being present in the engine for quite a number of years now and won't cause issues for a normal user unless they issue mp3 commands directly or have `developer` set. Is there any output from anything in CCDAudio that normally prints just from playing normally?

If anything I'd just change this to add an additional cvar to enable/disable logging from this module with the caveat that enabling logging is potentially unsafe.

**Comment by SamVanheer** [comment]
Looks like it's all debug output only.

**Comment by shawns-valve** [comment]
These unsafe console prints were removed as of the Half-Life 25th anniversary update (December 2023 Steam build).
