### ISSUE TITLE
Damage Through

### ISSUE THREAD

**Issue by hashnimmo** [ValveSoftware/halflife#2319]
Download this [map](http://filebin.net/q9g0cv4fvpcy93kh/fy_hide.rar), extract it and install. Start a server with it and buy these weapons after you have spawned;

(Terrorist) **D3/AU-1** 
(Counter-Terrorist) **KRIEG 550 COMMANDO**

Choose a glass panel and stand on one side of it while the other team member stand on the other side of it. Now you both can see each other through the glass. Start shooting each other through the glass using the above weapons. Terrorist bullets seem to go through the glass and hit Counter-Terrorist and do more damage.

Maybe that's because they are using different guns? I can't test this right now so check if you can.

**Comment by StevenKal** [comment]
I've not checked the map, but this is certainely due to the G3/SG1 which has a better penetration power, of x3 (like AWP), means it can hit three successive things, while the SG550 (as the other assaults rifles or Desert Eagle) have a x2 penetration power.

**Comment by StevenKal** [comment]
This is certainely due to the G3/SG1 which has a better penetration power, of x3 (like AWP), means it can hit three successive things, while the SIG-550 (as the other assaults rifles or Desert Eagle) have a x2 penetration power.
This is a game behavior, due to the fact that weapon is more powerful (7.62mm caliber), like its base damage which is more too (80 vs 70 for the SIG-550).

**Comment by hashnimmo** [comment]
Thanks.

**Comment by kisak-valve** [comment]
Closing because this does not appear to be an issue.
