### ISSUE TITLE
[Feature Request] Block write access to SVC_PINGS

### ISSUE THREAD

**Issue by thedoorisstuck** [ValveSoftware/halflife#2382]
The amount of fake ping servers is keeping me up at nights.

**Comment by basuritashka** [comment]
Agreed. I am tired of that too.

**Comment by StevenKal** [comment]
You mean, is this causes you problem when it's used to set a fake ping to the bots (as a replacement for "BOT" in scoreboard), or for something else?

**Comment by StevenKal** [comment]
You mean, is this causes you problem when it's used to set a fake ping to the bots (as a replacement for "BOT" in scoreboard, in order to "trick" you about who is a bot, who isn't from that listing), or for something else?

**Comment by thedoorisstuck** [comment]
> You mean, is this causes you problem when it's used to set a fake ping to the bots (as a replacement for "BOT" in scoreboard, in order to "trick" you about who is a bot, who isn't from that listing), or for something else?

Close but not quite, server owners are setting the clients(real human players) ping to a low range on the scoreboard.

**Comment by StevenKal** [comment]
From my opinion, it's more used for the "bot trick" I've said.
About "yours", I'm guessing admins do that more in order to prevent some annoying complains from other players (like "please kick this high pinger he makes us lag, blablabla...", as I saw on my servers).

And about "bots", some people really need to understand that they are useful tool designed to make the human players stay longer, rather than see them moving on lambda social communities servers, etc.
And today, this is not like on the past, on the past we didn't really need bots to fill servers, there were less servers, less players, less games, etc., now using bots on start up is almost mandatory, and even with bots, a ton of "good" servers remain empty or barely frequented.
And tricking the ping for them is helpful regarding this goal.
I understand probably everyone prefer playing against humans, but when you spend time to set up a server and you have not the chance to have a community or group of friends playing frequently on it, using bots and faking a few infos as their pings is an alternative solution, in an attempt to bring more humans. Most of the servers's owners will agree with this, only players-only will dislike much.

**Comment by thedoorisstuck** [comment]
> From my opinion, it's more used for the "bot trick" I've said.
> About "yours", I'm guessing admins do that more in order to prevent some annoying complains from other players (like "please kick this high pinger he makes us lag, blablabla...", as I saw on my servers).
> 
> And about "bots", some people really need to understand that they are useful tool designed to make the human players stay longer, rather than see them moving on lambda social communities servers, etc.
> And today, this is not like on the past, on the past we didn't really need bots to fill servers, there were less servers, less players, less games, etc., now using bots on start up is almost mandatory, and even with bots, a ton of "good" servers remain empty or barely frequented.
> And tricking the ping for them is helpful regarding this goal.
> I understand probably everyone prefer playing against humans, but when you spend time to set up a server and you have not the chance to have a community or group of friends playing frequently on it, using bots and faking a few infos as their pings is an alternative solution, in an attempt to bring more humans. Most of the servers's owners will agree with this, only players-only will dislike much.

I explained and you still managed to completely miss the point. This has nothing to do with bots on the server. It's more about public servers that hide the actual players ping ( which still can be obtained through 'ping' command) to _fool_ the unsuspecting players to stay on the server while suffering bullet lag etc. because they see that their ping is in the normal range.

Now to address your concerns about spec-bots and alike, I personally don't care that they exist, what I do have a problem with is they're fooling unsuspecting players to waste their time joining empty servers, so it comes down to the server owner's level of respect towards the players and the time they put into growing their community which in that case is nothing but scummy tricks to hide the level of laziness and low quality servers because at the end of the day, players are not trying to have an unpleasant experience, in lieu they're looking for a fun server to spend time in.

**Comment by StevenKal** [comment]
I've talked about "yours", for the non-bot problem. But I agree your case is different than the both subjects I've explained.
Well, I didn't think there were such servers that faked the actual ping for the players themselves, this sounds a bit stupid to me, because if I go on another server at the opposite of the earth, I'll feel it while moving/shooting, faking this doesn't make good sense, at least when this is a little big, but for a medium range like 100<->150ms which is faked to like "50<->70", this can be a bit advantageous in order to make you stay.

So you request to do not make the server "fake YOUR ping" can be interesting, but blocking the alteration of the other's ping transmited to you is something else, and I personnaly disapprove...

**Comment by basuritashka** [comment]
I mean, you should **NOT** be able to fake server or player ping, that should be directly blocked, its insane the amount of servers who are faking pings to their players and making players connect to them to receive a beautiful slowhacking (or any other malicious things).

**Comment by 2010kohtep** [comment]
If you block the SVC_PINGS message, the ping will not be displayed at all in the scoreboard. The ```ping``` command refers to the commands that are processed by the server, not the client, because the client does not have information about the received packets of other players, what does not allow to calculate the real ping. When the ping command is executed, it is sent to the server, and the server forms a ping list in client console. This can also be faked. There is no real way to deal with this.

**Comment by thedoorisstuck** [comment]
cantfix
