### ISSUE TITLE
[CS] cstrike.ico

### ISSUE THREAD

**Issue by 10th** [ValveSoftware/halflife#2460]
If you like my CS 16х16 ico version, you can update it.

![image](https://user-images.githubusercontent.com/11433503/58278380-8f12e700-7da4-11e9-804f-189f77fb72f9.png)

[cstrike_new.zip](https://github.com/ValveSoftware/halflife/files/3213037/cstrike_new.zip)

**Comment by hashnimmo** [comment]
No offence but your icon is bad, and too blurry. Certainly not up to a game studio quality.

Also I don't see any reason not to update the current default game icon to a 256 x 256 size version to support new operating systems with large icon views. So that people can also make large desktop shortcuts than always launching the game from the Steam game library.

**Comment by GBCS-PRO** [comment]
Having a higher res icon idea is good. But the execution done is bad. I'll try to up-scale the current icon and see how it'd turn out.

**Comment by GBCS-PRO** [comment]
![cstrike 256](https://user-images.githubusercontent.com/50755959/58278489-ced9ce80-7da4-11e9-82eb-34cd0fdbd7e3.png)
Try this one. I used AI upscale and edited the image a bit..

**Comment by 10th** [comment]
Now compare the picture 16x16!!! icons (GBCS-PRO version with mine) and tell me about the implementation quality and blur.

**Comment by GBCS-PRO** [comment]
Nope, even in 16x16 mine looks hella better and reserves the details (even if a little bit blurry)
