### ISSUE TITLE
[HLSDK] Game doesn't check else if's?

### ISSUE THREAD

**Issue by BlackShadow306** [ValveSoftware/halflife#2474]
I believe game doesn't check "else if" statements.

For example:

`	

        }
	else if ( m_flReleaseThrow > 0 )
	{
		// we've finished the throw, restart.
		m_flStartThrow = 0;

		if ( m_pPlayer->m_rgAmmo[ m_iPrimaryAmmoType ] )
		{
			SendWeaponAnim( HANDGRENADE_DRAW );
		}
		else
		{
			RetireWeapon();
			return;
		}

`

It doesn't animate draw animation after player threw a nade.

**Comment by SamVanheer** [comment]
`else if` is part of the C++ language, not the game itself. The code executes just fine, the problem is `m_flReleaseThrow` is always 0 by this point since it's zeroed out:
https://github.com/ValveSoftware/halflife/blob/c76dd531a79a176eef7cdbca5a80811123afbbe2/dlls/handgrenade.cpp#L176

Commenting this line out will fix the animation.

**Comment by BlackShadow306** [comment]
I've tried but didn't worked. Maybe something from my side?

**Comment by SamVanheer** [comment]
Did you recompile and place the dlls in the right place?

**Comment by BlackShadow306** [comment]
Yep, i've tried something else just to make sure everything is correct. But still nothing.

**Comment by SamVanheer** [comment]
I checked it again and it works when i do it. I don't know why this would fail to work.

What exactly did you change? Just the one line?

**Comment by BlackShadow306** [comment]
Ah, working like a charm now. It seems i skipped something.
