### ISSUE TITLE
[CS] [RU] translation

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [ValveSoftware/halflife#2508]
123

**Comment by afwn90cj93201nixr2e1re** [comment]
https://github.com/afwn90cj93201nixr2e1re/CounterStrike16Translation

Перевёл большинство строк для кс.
Формат
`// [Need some improvments]`
Требуются дополнительные обсуждения, так как везде по разному можно интерпретировать ключи.

`// [U] ` - различные варианты перевода, выбрать я так и не смог, предлагайте свои.

`// [No translate | start]` и `// [No translate | end]`
секции которые практически не переводились, их не особо много, большинство из них относится к Counter Strike Condition Zero, что странно и к какому-то режиму Career.

Также причиной отсутствия перевода некоторых ключей, является отсутсвие контекста, так как в файлах ресурсов часть из них отсутсвует.

**Comment by kisak-valve** [comment]
Hello @afwn90cj93201nixr2e1re, due to the fact this is an issue tracker instead of a general forum and the Valve developers use English, an untranslated Russian discussion makes this issue report not actionable.

Feel free to continue the discussion here and if there are translation improvement you'd like to suggest, drop them in #2311 or give me a ping (in English) with the end result of the discussion.

**Comment by afwn90cj93201nixr2e1re** [comment]
But mikela allow it. @kisak-valve

**Comment by kisak-valve** [comment]
Right, putting it another way, once you have something actionable for @mikela-valve to adjust in a game, let me know and I can re-open this issue report.

Whether the issue report is open or closed should not block the discussion but which strings that can be adjusted should be understandable in English.
