### ISSUE TITLE
To kisak.

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [ValveSoftware/halflife#2619]
Block issues non-commenting depended on github blacklist.

![изображение](https://user-images.githubusercontent.com/9306996/61718593-5e373a00-ad74-11e9-89c9-63efac05b6eb.png)

For example this issue (this, not on screenshot) can't be liked/commented from Sam and 
![изображение](https://user-images.githubusercontent.com/9306996/61718701-8d4dab80-ad74-11e9-8c87-a6444a1d2f33.png)

This is public tracker and we should allow commenting at all issues, from all ppls.

**Comment by afwn90cj93201nixr2e1re** [comment]
@kisak-valve

**Comment by kisak-valve** [comment]
Closing as invalid.

**Comment by afwn90cj93201nixr2e1re** [comment]
@kisak-valve what is invalid?

**Comment by afwn90cj93201nixr2e1re** [comment]
Create 2 account's, add first account to black list on second account, screate issue there from second account and try to comment from first.

@kisak-valve make issue tracker fully open. Not depended on black list.

**Comment by kisak-valve** [comment]
This issue report is literally a waste of time asking for there to be no access control on issue trackers in general because a third party is hypothetically wronged. It has nothing to do with halflife or the Goldsource engine. Issues are rarely locked and if they are, there usually is a good reason for them to have been locked. There's nothing blocking a new issue report from being made for constructive feedback.

Please stop calling me out, it will not end well.

**Comment by afwn90cj93201nixr2e1re** [comment]
Lol, wtf?
Im not talking bout new issues, which you gonna close, coz they duplicate old issues.
How we should workaround if there 2 issues, and in one of them we can't write comments?

@kisak-valve

**Comment by afwn90cj93201nixr2e1re** [comment]
>Please stop calling me out, it will not end well.

![изображение](https://user-images.githubusercontent.com/9306996/61813265-564fc680-ae56-11e9-88fb-f24378c50a46.png)
Very interesting, how we should communicate with you?

There no official email.
