### ISSUE TITLE
Fatal Errors!

### ISSUE THREAD

**Issue by zoruamonster** [ValveSoftware/halflife#2821]
https://github.com/ValveSoftware/halflife/pull/2803
https://github.com/ValveSoftware/halflife/pull/2805
https://github.com/ValveSoftware/halflife/pull/2806
https://github.com/ValveSoftware/halflife/pull/2807
https://github.com/ValveSoftware/halflife/pull/2808
https://github.com/ValveSoftware/halflife/pull/2809
https://github.com/ValveSoftware/halflife/pull/2810
https://github.com/ValveSoftware/halflife/pull/2811
https://github.com/ValveSoftware/halflife/pull/2812
https://github.com/ValveSoftware/halflife/pull/2813
https://github.com/ValveSoftware/halflife/pull/2814
https://github.com/ValveSoftware/halflife/pull/2815
https://github.com/ValveSoftware/halflife/pull/2816
https://github.com/ValveSoftware/halflife/pull/2817
https://github.com/ValveSoftware/halflife/pull/2818
https://github.com/ValveSoftware/halflife/pull/2819
https://github.com/ValveSoftware/halflife/pull/2820

??????

**Comment by tmp64** [comment]
WTH is all this??? Why would anyone create pull requests with only comments about errors instead of actual fixes?

**Comment by Sockman1** [comment]
Unless you have evidence of any of this breaking something in-game, please close this. Also this isn't proper use of pull requests, just describe the issue here.

**Comment by basuritashka** [comment]
@kisak-valve close this thread please.

**Comment by zoruamonster** [comment]
@Sockman1 @basuritashka  @kisak-valve why close ? it real errors found by static analyzer!

**Comment by zoruamonster** [comment]
https://github.com/ValveSoftware/halflife/pull/2805/files
if ( pszAmmo2() && !m_pPlayer->m_rgAmmo[SecondaryAmmoIndex()] )

SecondaryAmmoIndex == -1

**Comment by zoruamonster** [comment]
and etc

**Comment by kisak-valve** [comment]
Hello @zoruamonster, this is a fairly extreme example of how not to start a discussion. You chose to open a bunch of pull requests with non-functional changes and no attempt to explain why this needs attention.

Spamming the issue tracker like this is abusive behavior and unconstructive. If you have a specific issue and it has a functional impact on the game, then they should be discussed individually instead of a pile of vague and indirect comments which point out that a 20 year old game engine has rough edges.
