### ISSUE TITLE
Adding support half life maps to CS 1.6 or remove 'changelevel halflife.bsp' feature

### ISSUE THREAD

**Issue by zoruamonster** [ValveSoftware/halflife#2823]
Please add support half life maps in CS 1.6 or remove **changelevel crossfire.bsp** feature. 

For example in crossfire siren always beeps after sv_restart.

**Comment by LucesEnBabel** [comment]
No, this would break mods.

Want a solution? Don't change to crossfire.

**Comment by zoruamonster** [comment]
@LucesEnBabel nice!

**I found bug!!!**
Solution: **don't use this bug!**

**Comment by tmp64** [comment]
@zoruamonster 
Actually, this is not a bug. Loading maps in CS 1.6 from other mods (or base game) is not supported and there is no reason to support it.

**Comment by zoruamonster** [comment]
@tmp64 , yes, need remove support changelevel from another mod.

**Comment by regener** [comment]
This is caused by cross-shared resources, for example cstrike loads spr files from valve folder too, the same as it can load a map.

**Comment by CS-PRO1** [comment]
If you do remove this feature simply all goldsrc games/mods will cease to work. For example Condition zero uses many files from both 'valve' and 'cstrike' folders including maps. It is a bug within the map itself that only happens when it is loaded to any mod except for the core HL1 game.
@kisak-valve You can close this, thanks..

**Comment by zoruamonster** [comment]
@CS-PRO1 @kisak-valve need just add './../cstrike/maps/' for check map (function IsMapAvailable or how this function named)
