### ISSUE TITLE
[Half-Life: Opposing Force] Playing as spectator team in CTF mode

### ISSUE THREAD

**Issue by tyabus** [ValveSoftware/halflife#2897]
Steps to reproduce:
Launch any ctf map.
Join spectators team.
Write selectchar 1-7 in console. (may not work at first time).
And you are playing as spectator team (can pickup both team flags)!

**Comment by kisak-valve** [comment]
Hello @tyabus, this is already being tracked at #2846. Feel free to add your experience to the existing issue report.

Closing as a duplicate.

**Comment by Solokiller** [comment]
@kisak-valve this issue is not related to the one you linked. That issue covers spectator mode only being available in the capture the flag gamemode, not in the deathmatch and team deathmatch game modes.

This issue covers a bug where you can join the spectator team and then select a character to play as even though you're not in a real team. It allows you to walk around like players do, instead of flying like spectators do. You can also pick up weapons and items, including flags.

This happens because `CBasePlayer::Menu_Char_Input` doesn't check if the player is on a team/joining a team before processing the input.

A way to fix it would be to add this to the start of the method:
```
if (m_iNewTeamNum == 0)
{
	ClientPrint(pev, HUD_PRINTCONSOLE, "Can't change character; not in a team.\n");
	return false;
}
```

**Comment by kisak-valve** [comment]
Hello @Solokiller, without some indication of intent from a Valve dev, my initial assessment stands that this should be treated as a feature request instead of a separate bug.

**Comment by Solokiller** [comment]
I'm fairly certain it is a bug because it's accessing an array out of bounds as a result of using the team id as an index (id - 1, specators have id 0 so it becomes -1). When i ran it with a modern compiler it actually closed the game because it detected the out of bounds access.

Additionally you spawn with no HUD because the game doesn't give you a suit and you don't get the Pipe wrench, Barnacle grapple and Desert eagle like you normally get when you spawn, you can't pick up regular items (medkit, battery, powerups) because you don't have a suit, and you can pick up and carry both teams' flags (also items, but different) at the same time, though you can't bring them to the other teams' base to score points.

The game tells you "your" flag was stolen even though you're the one who picked up the flag. Dying and respawning places you back in specator flight mode.

**Comment by SamVanheer** [comment]
I just tried this since we have people playing today. This does indeed work and allows you to pick up both teams' flags. You can be killed by anybody and lack weapons but i can see how this could be exploited.
