### ISSUE TITLE
[GoldSrc] SV_ParseConsistencyResponse vulnerability

### ISSUE THREAD

**Issue by magister4813** [ValveSoftware/halflife#2980]
![Screenshot_2](https://user-images.githubusercontent.com/49805165/94366245-8c827900-00df-11eb-94e1-f8590101266c.png)

Users can exploit this by sending a fake **clc_fileconsistency** with length <= 0, causing hlds to close.
**Sys_Error** should be replaced with Con_Printf/Con_DPrintf.

**Comment by Solokiller** [comment]
The client should also be dropped from the server if this happens.

**Comment by Splatt581** [comment]
Same for _**SV_ParseMove**_:

![image](https://user-images.githubusercontent.com/31417200/98261902-06870700-1f96-11eb-94a0-39e92e862a1c.png)

**Comment by RauliTop** [comment]
@kisak-valve 
This issue needs to be tracked at ToDO list

**Comment by fire64** [comment]
It's 2023 and the bug hasn't been fixed yet.
Just checked it by sending incorrect clc_fileconsistency to my server.
As a result, the server crashed.

The server has been updated to the latest version, the error persists.

**Comment by WhiteMaterials** [comment]
Bad valve developers cant fix this issue

**Comment by 0Ky** [comment]
> Replying to https://github.com/ValveSoftware/halflife/issues/2980#issuecomment-722456655

@Splatt581 Can you create a separate issue for the crash caused by an invalid length of a crafted `clc_move` message type? Considering that this issue was reported four years ago and is still relevant and actively exploited, we may need to provide a PoC that demonstrates the exploit, so the devs can prioritize and address the issue.

@shawns-valve Can we get some closure on this issue? It's been around for a while and I've witnessed it firsthand post-25th anniversary update that crashed my game when a player joined my listen server with Steam Networking enabled:

![CrashSVParseMove](https://github.com/user-attachments/assets/bc02f0cf-d938-420b-b831-ff8950c96000)

**Comment by Splatt581** [comment]
> > Replying to [#2980 (comment)](https://github.com/ValveSoftware/halflife/issues/2980#issuecomment-722456655)
> 
> @Splatt581 Can you create a separate issue for the crash caused by an invalid length of a crafted `clc_move` message type? Considering that this issue was reported four years ago and is still relevant and actively exploited, we may need to provide a PoC that demonstrates the exploit, so the devs can prioritize and address the issue.

What engine build are you using? From my observations, in the latest update the exploit has been fixed for Windows and Linux binaries:
```
] version 
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
Exe build: 19:06:31 Oct  7 2024 (10210)
```
`Sys_Error` has been replaced by `Con_Printf` with `SV_DropClient`:
```
if ( (signed int)v3 <= 0 || (v1 = v2 + 2, (signed int)&v3[v2 + 2] > net_message.maxsize) )
  {
    Con_Printf(v1, "SV_ParseMove: invalid length: %d\n");
    SV_DropClient(v3, host_client, 0, "Invalid Move message");
LABEL_6:
    msg_badread = 1;
    return;
  }
```

**Comment by 0Ky** [comment]
@Splatt581 Ah, it seems like I had some bad timing. What a happy coincidence! I've updated my client and can confirm that both `SV_ParseMove` and `SV_ParseConsistencyResponse` issues were fixed in the latest `October 9, 2024`, update. The crash occurred in an older build.

I suppose this issue can be closed, thank you @shawns-valve!

**Comment by Splatt581** [comment]
> @Splatt581 Ah, it seems like I had some bad timing. What a happy coincidence! I've updated my client and can confirm that both `SV_ParseMove` and `SV_ParseConsistencyResponse` issues were fixed in the latest `October 9, 2024`, update. The crash occurred in an older build.
> 
> I suppose this issue can be closed, thank you @shawns-valve!

Agreed, I tested and confirm that both vulnerabilities are fixed in the latest build of the engine (10210). The issue can be closed.

**Comment by shawns-valve** [comment]
Closing per comments above.
