### ISSUE TITLE
[Half-Life] You can climb ladder faster in certain position (fix)

### ISSUE THREAD

**Issue by Aynekko** [ValveSoftware/halflife#3086]
When you climb the ladder you can, for example, face left side, then look directly up and press W+A or W+D which result in 2x climbing speed.

To fix this, put in the end of PM_LadderMove
```
float climbVel = pmove->velocity.Length();
if (fabs(climbVel) > MAX_CLIMB_SPEED)
pmove->velocity = pmove->velocity.Normalize() * MAX_CLIMB_SPEED;
```

**Comment by tmp64** [comment]
That's not a bug, that's a feature (in my opinion). Even CS:GO has it.

**Comment by Aynekko** [comment]
> That's not a bug, that's a feature (in my opinion). Even CS:GO has it.

Everybody got used to it, but it's still a bug :) well, they may not fix it if they prefer

**Comment by NukemD** [comment]
This feature has existed since the inception of the game, not a bug.

If you don't like Quake style physics, Half-Life isn't for you.

**Comment by Aynekko** [comment]
> This feature has existed since the inception of the game, not a bug.
> 
> If you don't like Quake style physics, Half-Life isn't for you.

"Fair" argument. Many things existed since the inception of the game. So why do we bother reporting issues here, maybe we could just count them all as features?

**Comment by NukemD** [comment]
You don't seem to understand that the way ladder physics has functioned for the past 23 years is not an issue. It's part of how Quake physics works and many engines with Quake lineage have the exact same functionality. What you seem to have issue with is Quake physics itself, which is why I said that Half-Life may not be for you if you don't like Quake style physics.

The Source engine has the exact same ladder system available via func_ladder, and as far as I'm aware, so does the CS:GO engine.

Just because Quake physics works in a way you don't expect it to, doesn't make it a bug.

**Comment by Aynekko** [comment]
> ladder physics

This is not "physics". It's simply an oversight. Don't you think that MAX_CLIMB_SPEED is called like this for a reason? You are not supposed to climb faster than this speed. Besides, I didn't change any physics at all, it's literally 3 simple lines of code. Just because it was never fixed doesn't make it a feature. I would rather wait what the devs would say about it :)

**Comment by NukemD** [comment]
If it was an oversight, you'd think that after 23+ years, several engine forks, several engine descendents, hundreds of mods and millions of eyeballs looking at it; Someone, somewhere would have done something. The fact is that nobody did anything because it was fine the way it was, and is still fine.

There is no bug, nor is there an oversight. This is part of Quake physics and this is how the community likes it. Many mods depend on ladders behaving the way they do, going in and completely changing how they function 23 years later is a non-starter.

This is why we can't have nice things. People like you come along and look for problems where there are none and ruin it for everyone.

**Comment by Aynekko** [comment]
> hundreds of mods

to be honest I totally forgot about some mods relying on that, so you have a point. However I'm still certain it was an oversight because clearly the feature wasn't working as intended all these years. The fact that the players abused it for so long that it became a feature, is a different story. I guess it should be considered after all.
Either way, I fixed that in my own mod, and the issue can be deleted or closed by admins if they feel so. Maybe someone else will find it useful too.

**Comment by NukemD** [comment]
That seems to be a common theme "oh hey I found this really old bug, let's patch it!" without thinking of the hundreds of mods and thousands of plugins that depends on specific aspects of the engine. I'm still very angry about the 2013 Steampipe update.

While it was a necessary evil to get cross platform support going, it changed a lot "under the hood" of the HL engine that didn't need to be changed for that goal. One of them was updating the network protocol from 47 to 48, the one used by Source. This caused huge swaths of old plugins and mods to break and be lost because there was no source available to recompile against the updated engine, and many mods have to be run on old WON installs now, or a backup of the last known HL engine before the Steampipe update.
