### ISSUE TITLE
Unable to download files with spaces from server.

### ISSUE THREAD

**Issue by MaNaReaver** [ValveSoftware/halflife#3274]
If a map/plugin precaches a file that has spaces in them, it wouldn't be downloaded as it divides the file into multiple files, a space being the delimiter. This prevents players from joining the server as they're stuck in a "Verifying resources..." loop until a map restart is issued. Mappers therefore usually add resources that do not have spaces as delimiters in them, but some forget to make the changes.

For example, a map like **ze_countryroads** requires the following file to run:
> sound/ze_countryroads/Warriyo - Mortals.wav

However, the player cannot download this file from a multiplayer server, as it's split up into the following:
> Error: server failed to transmit file 'sound/ze_countryroads/Warriyo'
> Error: server failed to transmit file '-'
> Error: server failed to transmit file 'Mortals.wav'

A usual solution is to edit the BSP and remove the spaces in the precached file, however it's cumbersome to do for many such maps. A good solution for the engine would be to replace spaces to %20 such that the file can be downloaded correctly instead of being broken down.

**Comment by kisak-valve** [comment]
Hello @MaNaReaver, this issue is already being tracked at #2056. Since this issue report gives an example seen in the wild, which was lacking from the older issue report, I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/halflife/issues/2056#issuecomment-1135165934.

Closing in favor of the older issue report.
