### ISSUE TITLE
 half life 25 years anniversary update broke counter strike 1.6

### ISSUE THREAD

**Issue by sekalengrengginang** [ValveSoftware/halflife#3411]
![Screenshot_20231118_013956](https://github.com/ValveSoftware/halflife/assets/49896401/6be7ede9-bf31-40ce-bda6-0d8b38462617)
After this [update](https://store.steampowered.com/news/app/70/view/6941797379568863069?l=english) , cs 1.6 no longer works on Linux

**Comment by debasish-mihup** [comment]
same here on windows 11

**Comment by exegg** [comment]
Game is absolutely rekt.

**Comment by SamVanheer** [comment]
Switch Half-Life to the `steam_legacy` branch to continue playing Counter-Strike 1.6 for the time being.

**Comment by 4kliksAlex** [comment]
SWITCHING TO BETA WOULD FIX MY ISSUE AND MAKE CS1.6 LAUNCH.

![Properties - Counter-Strike 11_18_2023 4_12_18](https://github.com/ValveSoftware/halflife/assets/109423280/d956ae2f-8cb8-4920-936b-c4ebd88bb89d)

**Comment by SamVanheer** [comment]
Don't use the beta branch, it's an outdated version of the legacy branch.

**Comment by 4kliksAlex** [comment]
Okay, it seems to be true. Thanks buddy.
![hw dll Properties 11_18_2023 4_18_52](https://github.com/ValveSoftware/halflife/assets/109423280/ab9813d5-925d-48d6-b519-28817bbc2de9)

**Comment by MatiasEsf** [comment]
![Sin título-2](https://github.com/ValveSoftware/halflife/assets/49958478/a1616c6c-2ea8-4967-80e0-82e5235cbffc)

the icon appears upside down, please tell me this is a joke....

**Comment by necrophcodr** [comment]
This also applies to CS:CZ. When launching CS:CZ Deleted Scenes it simply crashes to desktop with no error message.

**Comment by janosharsanyi** [comment]
nice try, still not playing cs2

**Comment by Root-Core** [comment]
**Is this a Linux thread or is it the same error message on Windows systems?**

--------------

On my Linux system I encountered the same issue.

OS: Manjaro
Kernel: 6.6.1
GPU: AMD Mesa 23.1.9

**Comment by Erikk26** [comment]
On Windows 11:

![kép](https://github.com/ValveSoftware/halflife/assets/58042653/1fe6024c-65d1-4a9c-a360-d5bdcd7ede4d)
![kép](https://github.com/ValveSoftware/halflife/assets/58042653/6bd09b71-2b05-49e5-984f-99de1910163c)

**Comment by SamVanheer** [comment]
> > Don't use the beta branch, it's an outdated version of the legacy branch.
> 
> can you link the source of this?

The beta branch is used to test changes to the game. Right now it's the same as the steam_legacy branch but in the future it can be used for beta testing again and will break games and mods that require the steam_legacy branch instead. The updates released a few years ago were tested using the beta branch.

The only reason to use that branch is when you're beta testing changes so nobody should be using it right now.

**Comment by di57inct** [comment]
> On Windows 11:
> 
> ![kép](https://user-images.githubusercontent.com/58042653/284049256-1fe6024c-65d1-4a9c-a360-d5bdcd7ede4d.png) ![kép](https://user-images.githubusercontent.com/58042653/284049265-6bd09b71-2b05-49e5-984f-99de1910163c.png)

same here. problem still there after today's update.

**Comment by Root-Core** [comment]
This issue is about the native Linux version, the error message is of a different kind.
On Linux it is not possible to load the `client.so`.

On Windows are asserts failing, which is a "tool" for software engineers to verify certain program behaviors.

However, the error that occurs is in source files that implement the loading of blobs / files, which may be a similar enough or same error.

@kisak-valve - Should another issue be opened for the issues on Windows?

**Comment by namazso** [comment]
@Root-Core it's the exact same issue. LoadLibrary fails, returning a NULL hModule, which is why the assert fires.

**Comment by KarKarKarKarkarkar** [comment]
Client.dll error: Missing steam_friends and steam_utils in steam_api.dll.

**Comment by SamVanheer** [comment]
> Client.dll error: Missing steam_friends and steam_utils exports in steam_api.dll.

You need to run CS using the steam_legacy branch until the game has been updated.

As you can see on SteamDB they're working on it: https://steamdb.info/app/10/depots/

**Comment by SamVanheer** [comment]
The steam_legacy branch is how you run Counter-Strike right now.

**Comment by KarKarKarKarkarkar** [comment]
> ![Sin título-2](https://user-images.githubusercontent.com/49958478/283968383-a1616c6c-2ea8-4967-80e0-82e5235cbffc.jpg)
> 
> the icon appears upside down, please tell me this is a joke....

Yes, bad icon 😭

**Comment by sekalengrengginang** [comment]
last update fix this issue

**Comment by Erikk26** [comment]
Sometimes servers kicks me with this message:

![20231122194820_1](https://github.com/ValveSoftware/halflife/assets/58042653/ed6ae938-86ec-4c9f-b75c-7307bac8ce0b)

Btw will a future update make able to alt-tab down from game both in CS 1.6 and HL1?

**Comment by Natsheh11** [comment]
The game is literally Garbage after many many years they are making small updates amount to nothing, expecting the community to be satisfied incontrary its the other way around instead of making minor changes to the mods fix the dam goldsrc engine and improve the physics..

**Comment by Maxi605** [comment]
> The game is literally Garbage after many many years they are making small updates amount to nothing, expecting the community to be satisfied incontrary its the other way around instead of making minor changes to the mods fix the dam goldsrc engine and improve the physics..

It's to be expected that a game this old ceases to recieve updates. I can't agree that the game is "garbage", it's pretty much the same game as before.

This "minor changes" that you're complaining about are to fix issues that were previously present and new issues that came with the 25th anniversary update, they're not useless, they're fixing the mods.

You should keep your silly comments to yourself if you have no intention to provide proper feedback about issues and improvements.

**Comment by f88083** [comment]
My mods in CS1.6 stop working 🤦‍♂️

**Comment by Natsheh11** [comment]
> > The game is literally Garbage after many many years they are making small updates amount to nothing, expecting the community to be satisfied incontrary its the other way around instead of making minor changes to the mods fix the dam goldsrc engine and improve the physics..
> 
> It's to be expected that a game this old ceases to recieve updates. I can't agree that the game is "garbage", it's pretty much the same game as before.
> 
> This "minor changes" that you're complaining about are to fix issues that were previously present and new issues that came with the 25th anniversary update, they're not useless, they're fixing the mods.
> 
> You should keep your silly comments to yourself if you have no intention to provide proper feedback about issues and improvements.

First thing first i am allow to express my opinion like or not what i have stated is the truth, i have wasted precious amount of work creating mods and testing for the game but due the goldsrc tremendous bugs and limitations i gave up half way through so i see those "major updates" as useless updates since they don't listen to what the community suggest..

**Comment by Root-Core** [comment]
It's fixed for me on Linux, thanks to everybody involved. Especially the FOV fix helps a lot on 32:9.

It is a good update. Could they do more? Propably. Is the game old and dead? Yes. It still is fun though.

So no complains from my side and it was stated before, that the SDK will be released later. This should help modding quite a bit, so we should wait what they deliver and don't argue about something we can't change.

--------------

@Natsheh11 Most mods work again, you should open bug reports for everything that causes problems.
You stated, that you have encountered issues with the GoldSrc engine and Valve fixed most of them now.
You also stated, you gave up because of them, so fixing bugs and not adding big features is a bad thing to you?

--------------

@Erikk26 I can Alt+Tab out of GoldSrc games on Windows 11 and Linux. Windows needs some seconds, Linux is instant.

**Comment by kisak-valve** [comment]
Closing as fixed in the [2023-11-22](https://store.steampowered.com/news/app/10/view/3889483182499845804) Counter-Strike update.
