### ISSUE TITLE
Noticeable audio latency

### ISSUE THREAD

**Issue by tmp64** [ValveSoftware/halflife#3459]
I experience very high audio latency in the anniversary update. You can clearly hear it in the video when selecting and firing weapons.

https://youtu.be/m_7BPMDj0qE  
[Hardware info](https://gist.github.com/tmp64/9d3b83c4d2baee26f8a2924ca4e69f08)

**Comment by Paft** [comment]
https://github.com/ValveSoftware/halflife/issues/3460

**Comment by kisak-valve** [comment]
25th Anniversary Update: Audio delay issues when firing a weapon, walking, etc.

Issue transferred from https://github.com/ValveSoftware/halflife/issues/3460.
@rtxa posted on 2023-11-18T13:11:46:

With the new update, in Half-Life there are some audio delay issues when you are firing a weapon, walking, turning on/off the flashlight, etc. Basically if you fire a weapon, you can hear the sound some miliseconds later instead of being instant of what you see in the screen. This issue is similar to the one in Half-Life 2 which luckily you can fix by lowering the value of `snd_mixahead` to 0.05 but unfortunately this command is not available. Several players have told me they're experiencing this issue so I'm not the only one.
***
@3doplayer67484 commented on 2023-11-18T13:58:33:

> With the new update, in Half-Life there are some audio delay issues when you are firing a weapon, walking, turning on/off the flashlight, etc. Basically if you fire a weapon, you can hear the sound some miliseconds later instead of being instant of what you see in the screen. This issue is similar to the one in Half-Life 2 which luckily you can fix by lowering the value of `snd_mixahead` to 0.05 but unfortunately this command is not available. Several players have told me they're experiencing this issue so I'm not the only one.

you can fix it as its called _snd_mixahead in HL1 and in other GoldSrc games 
just set it to 0 in a config file somewhere or in autoexec to fix it

**Comment by JimGrim82** [comment]
Confirm.  Interestingly if you set **_snd_mixahead -0.07** (yes negative) it seems to counteract the issue, but it causes severe performance issues at the menus screen if left at this value and the game is restarted...

**Comment by pierow** [comment]
I ran some objective testing with this and recorded the delays. My findings show that the minimum audio delay in HL25 is more delayed than legacy build, and any negative `_snd_mixahead` values saved in the config.cfg to obtain even a reasonable delay result in max CPU usage of the core running the game and the game not responding upon launching the game.

Approximate results given 16ms of possible error due to 60fps video frames and 2-3 samples per listed result:

- Default `_snd_mixahead 0.1`:
   - HL25: 260ms delay
   - legacy HL: 75ms delay

- Reduced and no crash on launch:
   - `_snd_mixahead 0` for HL25: 155ms

- Lowest possible delay for each engine build without popping or stuttering on my PC:
   - HL25: 50ms with `_snd_mixahead -0.09` (must be applied after launching game, then unapplied before closing or it will hang on launch)
   - legacy HL: 25ms with `_snd_mixahead 0.05` (no issues on launch)

Testing done with a Realtek ALC1220 audio chipset.

**Comment by SamVanheer** [comment]
It looks like the engine no longer uses DirectSound and always uses wave output instead. Wave output is known to have a delay due to how it's implemented versus DirectSound's use of direct memory access. The DirectSound initialization code still exists so perhaps something is causing it to be skipped for some reason?

**Comment by SamVanheer** [comment]
Looks like that might have been it, the update that was just released prints `DirectSound initialized` instead of `Wave sound initialized`.

**Comment by pierow** [comment]
Yeah, I think it's fixed now.

**Comment by kisak-valve** [comment]
Closing per the last couple comments.

**Comment by kellerman** [comment]
Setting the value to 0.05 on both engines is still neceesary for me. Shouldn't it be like that by default? I struggled finding out what the problem was until I found @pierow 's post.
