### ISSUE TITLE
[HL25] "undefined symbol: SDL_GL_ResetAttributes" error on launch

### ISSUE THREAD

**Issue by FelixWolf** [ValveSoftware/halflife#3546]
OS:
Latest archlinux, fully updated using `pacman -Syu`.
```
[felix@crocuta Half-Life]$ uname -srm
Linux 6.6.2-arch1-1 x86_64
```

Error:
```
[felix@crocuta Half-Life]$ ./hl.sh
Error:/home/felix/.local/share/Steam/steamapps/common/Half-Life/hw.so: undefined symbol: SDL_GL_ResetAttributes
Could not load hw.so.
Please try again at a later time.
```

Tried re-installing SDL2 to see if that'd fix it, made sure that I have the relevant packages installed:
```
[felix@crocuta Half-Life]$ pacman -Qq | grep sdl
lib32-sdl12-compat
lib32-sdl2
lib32-sdl2_image
lib32-sdl2_mixer
lib32-sdl2_ttf
lib32-sdl_image
sdl12-compat
sdl2
sdl2_image
sdl2_mixer
sdl2_net
sdl2_ttf
sdl_image
sdl_net
sdl_sound
sdl_ttf
```

**Comment by SamVanheer** [comment]
The game relies on the SDL2 library that ships with the Steam runtime since the anniversary update: https://steamdb.info/depot/8/history/?changeid=M:2809540380682473923

It should not be using the system version.

See https://github.com/ValveSoftware/steam-runtime for more information about the runtime. To use it you need to include the paths in `LD_LIBRARY_PATH`.

To find which paths to use you can look at this tutorial: https://twhl.info/wiki/page/Half-Life_Programming_-_Debugging#Setting_the_library_paths

When launching through Steam the paths are automatically set up for you.

The shell script might not be setting up the correct paths so that should be reviewed.

**Comment by a1batross** [comment]
To run Half-Life within Steam Runtime:

```
~/.steam/steam/ubuntu12_32/steam-runtime/run.sh ./hl.sh
```

**Comment by FelixWolf** [comment]
> ~/.steam/steam/ubuntu12_32/steam-runtime/run.sh ./hl.sh

This unfortunately doesn't seem to solve the problem.
I should note, that it doesn't launch when running directly from steam, which is why I am trying to run it from a terminal window.
When launching from steam, it says "Launching", then immediately goes back to "Play".

**Comment by SamVanheer** [comment]
Try reinstalling the game.

**Comment by FelixWolf** [comment]
> Try reinstalling the game.

Well I'll be darned, that worked. Surprised that validating it didn't solve it.
Thanks!
