### ISSUE TITLE
[HL25] Linux HLDS via steamcmd fails to start after latest update

### ISSUE THREAD

**Issue by TheStormN** [ValveSoftware/halflife#3576]
When using the `hlds_run` script the server fails to start with issues about the bundled `libstdc++.so.6`
```
Error:./libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/steam/hlds/filesystem_stdio.so)
```

A workaround is to delete both `libstdc++.so.6` and `libgcc_s.so.1`.

Please, before releasing something at least try to run it after compiling. :)

**Comment by djearthquake** [comment]
Deleting those files does not recover all distros. For instance on Debian Bookworm, that only makes matter worse.

**Comment by JoelTroch** [comment]
Seems to be related to #3455

**Comment by MegaBrutal** [comment]
I manually ship a newer version of ``libstdc++.so.6`` for my HLDS installs, replacing the one installed by SteamCMD. I'd also really appreciate if Valve would ship a newer version of the lib because compiled Metamod plugins also require a newer ABI, so you either need to build a chroot or container for an extremely old end-of-life Linux distro to build for the old ABI or replace the lib manually with a newer one.

**Comment by djearthquake** [comment]
https://github.com/djearthquake/amxx/blob/main/hlds/hlds_fix.sh

Here is a script that I fixed 2 Debian machines with. The trick becomes to stop using hlds update script since it re-corrupts.

**Comment by MrCoala** [comment]
So the problem is related to the supplied ABI being too old? This bug also broke all of my hlds server instances, and I fixed it by deleting the one that was shipped by steamcmd and using the one from the system:

`cp /usr/lib32/libstdc++.so.6 .`

**Comment by TheStormN** [comment]
You don't even need to copy it. Deletion is enough.

**Comment by MegaBrutal** [comment]
Seems to be fixed: libstdc++.so.6 is not shipped with HLDS installations anymore.
This also means that a system-wide libstdc++ needs to be installed for slim installations, such as Docker images (on Debian Bookworm, the package name is libstdc++:i386).
This change must have happened in the last few days, because an image built 2 days ago still had the library (albeit an updated one).

**Comment by djearthquake** [comment]
I just ran update and HLDS appears to be corrected thankfully.

**Comment by ImBenny95** [comment]
Deleting libstdc++.so.6 from main folder got it fixed to me!

**Comment by TheStormN** [comment]
This seems to be resolved in the latest updates, so I'm closing the issue.
