### ISSUE TITLE
[HL25] bugs with r_shadows

### ISSUE THREAD

**Issue by IrisWasTaken1** [ValveSoftware/halflife#3595]
Z-fighting occurs with all shadows, and some models (notably sitting scientists) have their shadows rendered inside themselves

**Comment by nulcow** [comment]
I believe this has been an issue since r_shadows was first implemented. Because of the rendering technique used, it is impossible to stop visual bugs like this without making the shadows fully opaque (similar to Quake III, which uses the same shadow system), or significantly modifying the renderer to use different shadows.

**Comment by RyanGlade** [comment]
> I believe this has been an issue since r_shadows was first implemented. Because of the rendering technique used, it is impossible to stop visual bugs like this without making the shadows fully opaque (similar to Quake III, which uses the same shadow system), or significantly modifying the renderer to use different shadows. Do correct me if I'm wrong, however.

[Solokiller's Half-Life Asset Manager](https://github.com/SamVanheer/HalfLifeAssetManager) has it's own shadow z-fighting fix, maybe something similar to that could be used

**Comment by shawns-valve** [comment]
This isn't something we plan to address in the official engine; the goal here was just to unblock the r_shadows command as it originally existed for people who wanted to play with it, but it's not a fully supported feature.
