### ISSUE TITLE
[HL25] joypitchsensitivity is getting reset to 0

### ISSUE THREAD

**Issue by FreeSlave** [ValveSoftware/halflife#3621]
The value of `joypitchsensitivity` cvar gets reset to 0 when loading a map or the save in the mod or official addon (e.g. Blue Shift), at least on Linux. It doesn't get reset in Half-Life. Mods and Blue Shift also don't exhibit this behavior on `steam_legacy` branch, so it has something to do with the anniversary update.

**Comment by FreeSlave** [comment]
I checked on Windows and it has the same issue

**Comment by FreeSlave** [comment]
No longer an issue on the current version

**Comment by a1batross** [comment]
I've ran Half-Life under debugger and set watchpoint to joypitchsensitivity->value address. It gets changed by ClientDLL_CreateMove.

Judging by decompile of this function, it gets reset if client.dll doesn't define `joysupported` cvar to non-zero value.
![image](https://github.com/user-attachments/assets/44db49a3-b665-4c4c-bc1f-b285aa57f9a1)

Half-Life 25-th anniversary SDK adds it: https://github.com/ValveSoftware/halflife/blame/b1b5cf5892918535619b2937bb927e46cb097ba1/ricochet/cl_dll/inputw32.cpp#L930

Because it's not documented anywhere and cvar itself seemingly has no use in client.dll, it leads to confusion amongst mod developers, who didn't synced with HL25 SDK.
