### ISSUE TITLE
[HL25] Font rendering doesn't work on linux using Proton when your system has the original Tahoma and Trebuchet MS fonts

### ISSUE THREAD

**Issue by PonyRoleplayer** [ValveSoftware/halflife#3863]
I know no one's probably going to bother with this bug, but here it goes.

For some reason, font rendering doesn't work when your system has installed the 'Tahoma' and 'Trebuchet MS' fonts from Windows XP
![image](https://github.com/user-attachments/assets/252b7fce-332f-4f9c-b5c7-f119c61773ad)

![image](https://github.com/user-attachments/assets/5c9d3ebb-2237-47c9-a236-e7f5bcd20518)

![image](https://github.com/user-attachments/assets/e1e94814-0951-4ff4-9c1c-d0cacb6d784a)

![image](https://github.com/user-attachments/assets/6a5e52ad-b9c9-4da5-b370-ea110054f018)

This is Linux Mint, and I was using this version of Proton, and Proton experimental. I tried others, and same results. I was trying to play a Half-Life mod, that's why I'm running Proton.

Anyway, the fix for me was to use any other system font in the TrackerScheme.res file.

**Comment by kisak-valve** [comment]
Hello @PonyRoleplayer, we're tracking issues with games run with Proton in the Proton issue tracker. Also, we're using one issue report per unofficially supported game title when run with Proton. Since this issue report is fairly well written, I've gone ahead and transferred it to https://github.com/ValveSoftware/Proton/issues/4850#issuecomment-2475355401.

Running the Windows variant of the game on Linux is out of scope for this issue tracker.

**Comment by sabianroberts** [comment]
@PonyRoleplayer you can put the fonts into the native Linux version's TrackerScheme.res file :)

**Comment by PonyRoleplayer** [comment]
Thanks for moving it where it belongs!

@sabianroberts That's the problem, using proton it loads the fonts you have installed in your system. I had the original Tahoma and Trebuchet MS fonts installed and they didn't render. If I changed them to something like Ubuntu or Noto, or even a fake Tahoma font that had no antialising on purpose, it rendered it properly.

There's something going on with the old original fonts.

**Comment by sabianroberts** [comment]
> Thanks for moving it where it belongs!
> 
> @sabianroberts That's the problem, using proton it loads the fonts you have installed in your system. I had the original Tahoma and Trebuchet MS fonts installed and they didn't render. If I changed them to something like Ubuntu or Noto, or even a fake Tahoma font that had no antialising on purpose, it rendered it properly.
> 
> There's something going on with the old original fonts.

TrackerScheme.res has a field at the bottom for custom fonts that aren't installed in the system. This is where hl_linux's fonts are defined. Maybe try adding the path to the font files there (optimally, place copies of them in your resource folder)?

It would be nice for Valve to be able to use the original Tahoma and Trebuchet MS fonts as is on hl_linux, but due to pesky copyright laws, Valve aren't allowed to redistribute them I presume. The only reason the fonts are in use on the Windows version is because Microsoft owns the fonts and bundles them with Windows. 

I can assure you that there is nothing wrong with the fonts themselves and they have been mostly unmodified since they were originally packaged with Windows XP in 2001.

**Comment by PonyRoleplayer** [comment]
> Replying to https://github.com/ValveSoftware/halflife/issues/3863#issuecomment-2476789370

I know Valve has it's own Tahoma font bundled in the platform/resource folder, but they don't seem to be the same. They're signed differently and weight a little less than the ones I got from Windows XP SP3. If I run the native linux version, it works well with no issues, fonts render as they should. But if I use Proton, and I have to use it in order to play a mod, then the font rendering breaks using specifically the Tahoma and Trebuchet MS from Windows XP SP3 in my system. I came across this bug because I was theming my Linux Mint to look like XP Royale for the giggles, and wanted to use the original fonts for windows and text.

I haven't tried using another distro, but I imagine the issue is replicable. Although the original fonts can't be distributed, I imagine.
