### ISSUE TITLE
[HL1][Feature Request] Add an option to adjust FOV

### ISSUE THREAD

**Issue by thegreatprophetzarquon** [ValveSoftware/halflife#450]
Currently there is no option to adjust FOV in-game. The default FOV is too low for widescreen monitors (it gives me a headache). Changing FOV is currently considered a cheat in CS1.6, but is not a cheat in Half-Life (or any other non-CS game). While CS FOV should probably be left alone, a FOV slider (TF2 style) in Half-Life would be nice.

Old Thread: https://github.com/ValveSoftware/steam-for-linux/issues/1434

**Comment by omen23** [comment]
i just realised this ... playing cstrike for years and then not ... i didnt even realize "what i was missing". FFS carmack implemented "cg_fov" 
https://steamcommunity.com/sharedfiles/filedetails/?id=165867114
we even got a guide ... 
what game is more competitive than quake3 ?
add a FOV cvar, I demand it as programmer and player!
kind regards

**Comment by BlackShadow306** [comment]
just leaving this here and this issue can be closed.

You can adjust your FOV in Half-Life typing "default_fov <value> (default is 90)"

@kisak-valve This issue can be closed.

**Comment by nurky** [comment]
CS 1.6 needs to allow a maximum FOV of at least 120 or 150.
Playing on ultrawide screen:
![image](https://user-images.githubusercontent.com/55628546/69348894-318a2500-0c77-11ea-993b-5341bbc08e13.png)
If no patch is going to be ruled out then I'll reverse engineer the client and make my own tool.

**Comment by BlackShadow** [comment]
> CS 1.6 needs to allow a maximum FOV of at least 120 or 150.
> Playing on ultrawide screen:
> ![image](https://user-images.githubusercontent.com/55628546/69348894-318a2500-0c77-11ea-993b-5341bbc08e13.png)
> If no patch is going to be ruled out then I'll reverse engineer the client and make my own tool.

default_fov is disabled by default because it counts as a cheat in Counter-Strike. Even if you reverse engineer client.dll you won't able to join any community servers because your client.dll will differ than the actual CS's client.dll. And also editing client.dll will get you a VAC ban in result. Also there's already a reverse engineered CS in Github.

**Comment by nurky** [comment]
@BlackShadow I definitely agree with you, but this would be a memory hack instead of a custom client DLL, I have a ultra widescreen and I can't play like this can I?

The purpose of the tool is to tap inside the GoldSrc engine and change the global variable for the FOV because in 1.6 the default_fov command does not change anything within the assembly so I'll have to make a workaround considering that.

Also why not allow default_fov under sv_cheats conditions? That would at least be okay, just like in CS:GO where you are required to have sv_cheats enabled in order to use fov_cs_debug.

**Comment by BlackShadow** [comment]
Memory hacks also can be detected by VAC. I don't think FOV change will applied to the game but widescreen support surely can be added. In the meantime you can use widescreen weapon fix made by community (You can find it on Google) and also try 16:9 with it. It's not the best result, but hey it's something. Or just completely use 4:3 . I don't know how 4:3 will result in a widescreen though.

**Comment by BlackShadow** [comment]
Memory hacks also can be detected by VAC. I don't think FOV change will applied to the game but widescreen support surely can be added. In the meantime you can try widescreen weapon fix made by community (You can find it on Google)  with aspect ratio 16:9. It's not the best result, but hey it's something. Or just completely use 4:3 . I don't know how 4:3 will result in a widescreen though.

**Comment by thegreatprophetzarquon** [comment]
Congrats on the update!
