### ISSUE TITLE
[BUG] Mouse acceleration and zoom

### ISSUE THREAD

**Issue by MPNumB** [ValveSoftware/halflife#456]
Whenever player is in zoom while having m_customaccel enabled, field of view calculation fails.

Me being one of the people, who is using mouse acceleration... Well this gets quite inconvenient.

At the end of sensitivity formula do not forget

```
if( pev->fov < 45.0 ) // sniper zoom
 final_sensitivity *= ( ( pev->fov / 90.0 ) * cvar->zoom_sensitivity_ratio )
else // non-sniper zoom
 final_sensitivity *= ( pev->fov / 90.0 )
```

**Comment by longboardtard** [comment]
Why is this issue closed? This issue is still present. Zoom sensitivity response is wrong when zoomed in, and even worse with secondary zoom (note this happens as the thread mentions, with m_customaccel on). In a nutshell, movements in my mouse do not get translated properly to movements of the crosshair on screen, I have to move the mouse like hell to get any reasonable movement at all in my crosshair. This is an internal issue of the engine.

I use:
`m_rawinput 1`
`sensitivity 2`
`m_customaccel 0.18`
`zoom_sensitivity_ratio 1.2`
