### ISSUE TITLE
FPS problem since update

### ISSUE THREAD

**Issue by SoneTOne** [ValveSoftware/halflife#460]
Since the new update,it's basically impossible to me to play CS 1.6,my FPS doesn't go above 4,i tried everything and it still doesn't work.

![xs1LGNg](https://f.cloud.github.com/assets/3659022/180077/55b57aea-7c20-11e2-97ea-5ee684585226.jpg)

I really hope someone can help me.

Thanks.

**Comment by keeeennnji** [comment]
@ghost where do i put opengl32 file ??

**Comment by SamVanheer** [comment]
@keeeennnji That user's account was deleted so you won't get a response from them.

Custom opengl32 dlls are deleted by the engine on startup so that won't help you. I'm sure his comment was also referring to the presence of it, not the absence. The correct opengl32 dll is loaded by the engine from a system directory so it shouldn't cause any problems on its own.

**Comment by shawns-valve** [comment]
Closing due to age. If you're having problems on the current Steam version Counter-Strike, please open a new issue.
