### ISSUE TITLE
cs 1.6 downloading files from servers

### ISSUE THREAD

**Issue by roymor** [ValveSoftware/halflife#505]
since the update when trying to connect servers, im downloading files from the server and at the end when its trying to connect I'm getting alot of errors like : 

No detail texture mapping file: maps/de_dust2_detail.txt
No detail texture mapping file: maps/iGz_Nofalldamage_pole_detail.txt
Mod_LoadBrushModel: models/iGz_HnS_Blockmaker/iGz_Nofalldamage_pole.mdl has wrong version number (1836345404 should be 30)

Error: could not load file  dels/iGz_HnS_Blockmaker/iGz_honey.mdl
Model  dels/iGz_HnS_Blockmaker/iGz_honey.mdl not found and not available from server
Cannot continue without model  dels/iGz_HnS_Blockmaker/iGz_honey.mdl, disconnecting

Thats a problem because I've checked my cstrike folder and I got those files in it but im still getting this error
its seems that the server doesnt recognize that I got the files in my cstrike and he even can transfer the files for me correctly because you can see first its says couldn't load then its says the file is not availble from server

and this problem happens in alot of files WAD, TXT, BSP, MDL, SPT
after the patch the servers have problems with transfering the files to the user / recognizing that the user have them in his cstrike folder

PLEASE FIX ASAP!!!!!!
this happend to some of my friends aswell so its not a problem with my computer..

**Comment by miguelk5** [comment]
Quick fix for this issue !
Since defintly this bug still happening  , but just with some map that includes .wad files like as_tundra. The fix is just use fast download feature :

cstrike / server.cfg 

add : sv_downloadurl "http://yourwebsite/my_cstrike/"

Then , create such directory on the root of your webspace .

Add there each .wad file that any map could need , important respect folder structure , example (sounds/monster.wav   , overview/map.bmp)   

Also i copied all needed files inside  a folder called "my_cstrike/cstrike_downloads"  because the steam version of CS1.6 download files inside cstrike_downloads folder
