### ISSUE TITLE
[HL:OF] sniper sight glitch

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/halflife#851]
If you zoom with sniper rifle, and then load a save, sniper sight doesn't go away
video: http://youtu.be/OgnVd4Lau4s

**Comment by Solokiller** [comment]
This happens because `pev->fov` isn't saved and restored. This can be fixed by adding the following line:
```
pev->fov = m_iFOV;
```

Here:
https://github.com/ValveSoftware/halflife/blob/c7240b965743a53a29491dd49320c88eecf6257b/dlls/player.cpp#L3064-L3066

This also affects the Crossbow in all Half-Life 1 based games.

Note that in the SDK if this is fixed the exact opposite problem will start happening because the SDK does not restore the fov on the client side.

These lines here need to be commented out for that to be fixed:
https://github.com/ValveSoftware/halflife/blob/c7240b965743a53a29491dd49320c88eecf6257b/cl_dll/hud.cpp#L630-L632

As noted in the function prediction is supposed to handle fov locally, but it doesn't account for restoring non-default fov values.

Opposing Force doesn't have this problem because it has an extra condition in that if check that causes it to only work if the current game is `tfc`, which it would only be if you renamed the `gearbox` directory to `tfc` before running the game.

**Comment by kisak-valve** [comment]
Hello @Solokiller, due to the low quality initial report by a user that's turned into a ghost and references a dead link, can you create a new issue report? This request is also to workaround a Github bug where issue reports from users that have turned into a ghost are no longer indexed by Github's search engine. Feel free to reference this issue report to maintain continuity if you want.

**Comment by kisak-valve** [comment]
Closing in favor of #3044.

**Comment by Solokiller** [comment]
I've also reported the issue with `m_fInZoom` as a separate issue here: #3045
